"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

type Language = "en" | "fr" | "de" | "es"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: "Home",
    catalog: "Catalog",
    news: "News",
    contact: "Contact",
    search: "Search by name or number...",
    cart: "Cart",
    heroTitle: "Find your perfect Lorcana card",
    heroSubtitle: "Discover, filter and collect your favorite cards",
    browseCatalog: "Browse Cards",
    // Home page features
    legendaryCards: "Legendary Cards",
    legendaryCardsDesc: "Discover rare and legendary cards from all Lorcana sets",
    foilVariants: "Foil Variants",
    foilVariantsDesc: "Premium foil versions with stunning holographic effects",
    advancedFilters: "Advanced Filters",
    advancedFiltersDesc: "Find exactly what you need with powerful search tools",
    filters: "Filters",
    type: "Type",
    set: "Set / Collection",
    rarity: "Rarity",
    cardNumber: "Card Number",
    priceRange: "Price Range",
    version: "Version",
    versionAvailability: "Version Availability",
    allVersions: "All Versions",
    normalOnly: "Normal Only",
    foilOnly: "Foil Only",
    bothAvailable: "Both Available",
    stockAvailability: "Stock Availability",
    sortBy: "Sort By",
    gridView: "Grid View",
    listView: "List View",
    viewLabel: "View",
    addToCart: "Add to Cart",
    processing: "Processing...",
    cardUnavailable: "This card is currently unavailable in all versions.",
    goBack: "Go Back",
    normal: "Normal",
    foil: "Foil",
    character: "Character",
    item: "Item",
    action: "Action",
    song: "Song",
    common: "Common",
    uncommon: "Uncommon",
    rare: "Rare",
    superRare: "Super Rare",
    legendary: "Legendary",
    enchanted: "Enchanted",
    firstChapter: "The First Chapter",
    riseOfFloodborn: "Rise of the Floodborn",
    intoInklands: "Into the Inklands",
    ursulaReturn: "Ursula's Return",
    shimmering: "Shimmering Skies",
    azurite: "Azurite Sea",
    total: "Total",
    checkout: "Checkout",
    emptyCart: "Your cart is empty",
    about: "About",
    privacy: "Privacy Policy",
    copyright: "© 2025 GA Company. All rights reserved.",
    // Footer
    lorcanasingles: "Lorcana Singles",
    links: "Links",
    followUs: "Follow Us",
    nameAZ: "Name (A-Z)",
    nameZA: "Name (Z-A)",
    priceLowHigh: "Price (Low to High)",
    priceHighLow: "Price (High to Low)",
    raritySort: "Rarity",
    cardNumberLowHigh: "Card Number (Low to High)",
    cardNumberHighLow: "Card Number (High to Low)",
    // Common UI
    viewStore: "View Store",
    quantity: "Quantity",
    loading: "Loading...",
    loadingSubmissions: "Loading submissions...",
    loadingLogs: "Loading activity logs...",
    saving: "Saving...",
    save: "Save",
    saveAll: "Save All Changes",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    error: "Error",
    success: "Success",
    buyNow: "Buy Now",
    outOfStock: "Out of Stock",
    each: "each",
    approve: "Approve",
    reject: "Reject",
    approvePublish: "Approve & Publish",
    rejectSubmission: "Reject Submission",
    // Orders
    orders: "Orders",
    orderDetails: "Order Details",
    ordersDescription: "Manage and review all orders placed in the store",
    customer: "Customer",
    email: "Email",
    customerName: "Name",
    paymentInfo: "Payment Information",
    paymentId: "Payment ID",
    reference: "Reference",
    paymentStatus: "Status",
    paymentMethod: "Method",
    paidAt: "Paid",
    products: "Products",
    quantity: "Quantity",
    totalOrders: "Total Orders",
    totalRevenue: "Total Revenue",
    productsSold: "Products Sold",
    approvedOrders: "Approved orders",
    soldCards: "Cards sold",
    searchOrders: "Search by email, payment ID or reference...",
    allOrders: "All Orders",
    noOrders: "No orders yet",
    noOrdersFound: "No orders found",
    loadingOrders: "Loading orders...",
    view: "View",
    date: "Date",
    items: "Items",
    status: "Status",
    actions: "Actions",
    // Status
    approved: "Approved",
    pending: "Pending",
    rejected: "Rejected",
    cancelled: "Cancelled",
    refunded: "Refunded",
    // Inventory
    inventoryManagement: "Inventory Management",
    inventoryDescription: "Manage stock and prices for all cards",
    totalCards: "Total Cards",
    normalStock: "Normal Stock",
    foilStock: "Foil Stock",
    inventoryValue: "Inventory Value",
    searchInventory: "Search by name, card number, or set...",
    stockStatus: "Stock Status",
    allStock: "All Stock",
    allStockStatus: "All Stock Status",
    inStock: "In Stock",
    lowStock: "Low Stock",
    stockType: "Stock Type",
    hasNormal: "Has Normal Stock",
    hasFoil: "Has Foil Stock",
    hasBoth: "Has Both",
    all: "All",
    allTypes: "All Types",
    allSets: "All Sets",
    allRarities: "All Rarities",
    clearFilters: "Clear Filters",
    showingCards: "Showing",
    ofCards: "of",
    cards: "cards",
    price: "Price",
    foilPriceLabel: "Foil Price",
    name: "Name",
    cardNum: "Card #",
    // Stock badges
    lowStockBadge: "Low Stock",
    outOfStockBadge: "Out of Stock",
  },
  fr: {
    home: "Accueil",
    catalog: "Catalogue",
    news: "Actualités",
    contact: "Contact",
    search: "Rechercher par nom ou numéro...",
    cart: "Panier",
    heroTitle: "Trouvez votre carte Lorcana parfaite",
    heroSubtitle: "Découvrez, filtrez et collectionnez vos cartes préférées",
    browseCatalog: "Parcourir les cartes",
    // Home page features  
    legendaryCards: "Cartes Légendaires",
    legendaryCardsDesc: "Découvrez des cartes rares et légendaires de tous les sets Lorcana",
    foilVariants: "Variantes Foil",
    foilVariantsDesc: "Versions premium foil avec des effets holographiques époustouflants",
    advancedFilters: "Filtres Avancés",
    advancedFiltersDesc: "Trouvez exactement ce dont vous avez besoin avec des outils de recherche puissants",
    filters: "Filtres",
    type: "Type",
    set: "Set / Collection",
    rarity: "Rareté",
    cardNumber: "Numéro de carte",
    priceRange: "Gamme de prix",
    version: "Version",
    versionAvailability: "Disponibilité de Version",
    allVersions: "Toutes les Versions",
    normalOnly: "Normal Uniquement",
    foilOnly: "Foil Uniquement",
    bothAvailable: "Les Deux Disponibles",
    stockAvailability: "Disponibilité du Stock",
    sortBy: "Trier par",
    gridView: "Vue grille",
    listView: "Vue liste",
    viewLabel: "Vue",
    addToCart: "Ajouter au panier",
    processing: "Traitement...",
    cardUnavailable: "Cette carte n'est actuellement disponible dans aucune version.",
    goBack: "Retour",
    normal: "Normal",
    foil: "Foil",
    character: "Personnage",
    item: "Objet",
    action: "Action",
    song: "Chanson",
    common: "Commun",
    uncommon: "Peu commun",
    rare: "Rare",
    superRare: "Super Rare",
    legendary: "Légendaire",
    enchanted: "Enchanté",
    firstChapter: "Le Premier Chapitre",
    riseOfFloodborn: "Montée des Floodborn",
    intoInklands: "Dans les Inklands",
    ursulaReturn: "Le Retour d'Ursula",
    shimmering: "Cieux Scintillants",
    azurite: "Mer Azurite",
    total: "Total",
    checkout: "Commander",
    emptyCart: "Votre panier est vide",
    about: "À propos",
    privacy: "Politique de confidentialité",
    copyright: "© 2025 GA Company. Tous droits réservés.",
    // Footer
    lorcanasingles: "Singles Lorcana",
    links: "Liens",
    followUs: "Suivez-Nous",
    nameAZ: "Nom (A-Z)",
    nameZA: "Nom (Z-A)",
    priceLowHigh: "Prix (Bas à Élevé)",
    priceHighLow: "Prix (Élevé à Bas)",
    raritySort: "Rareté",
    cardNumberLowHigh: "Numéro de Carte (Bas à Élevé)",
    cardNumberHighLow: "Numéro de Carte (Élevé à Bas)",
    // Common UI
    viewStore: "Voir la Boutique",
    quantity: "Quantité",
    loading: "Chargement...",
    loadingSubmissions: "Chargement des soumissions...",
    loadingLogs: "Chargement des logs d'activité...",
    saving: "Enregistrement...",
    save: "Enregistrer",
    saveAll: "Enregistrer Tous les Changements",
    cancel: "Annuler",
    edit: "Modifier",
    delete: "Supprimer",
    error: "Erreur",
    success: "Succès",
    buyNow: "Acheter Maintenant",
    outOfStock: "Rupture de Stock",
    each: "chacun",
    approve: "Approuver",
    reject: "Rejeter",
    approvePublish: "Approuver et Publier",
    rejectSubmission: "Rejeter la Soumission",
    // Orders
    orders: "Commandes",
    orderDetails: "Détails de la Commande",
    ordersDescription: "Gérer et examiner toutes les commandes passées dans la boutique",
    customer: "Client",
    email: "Email",
    customerName: "Nom",
    paymentInfo: "Informations de Paiement",
    paymentId: "ID de Paiement",
    reference: "Référence",
    paymentStatus: "Statut",
    paymentMethod: "Méthode",
    paidAt: "Payé",
    products: "Produits",
    quantity: "Quantité",
    totalOrders: "Total Commandes",
    totalRevenue: "Revenus Totaux",
    productsSold: "Produits Vendus",
    approvedOrders: "Commandes approuvées",
    soldCards: "Cartes vendues",
    searchOrders: "Rechercher par email, ID de paiement ou référence...",
    allOrders: "Toutes les Commandes",
    noOrders: "Pas encore de commandes",
    noOrdersFound: "Aucune commande trouvée",
    loadingOrders: "Chargement des commandes...",
    view: "Voir",
    date: "Date",
    items: "Articles",
    status: "Statut",
    actions: "Actions",
    // Status
    approved: "Approuvé",
    pending: "En Attente",
    rejected: "Rejeté",
    cancelled: "Annulé",
    refunded: "Remboursé",
    // Inventory
    inventoryManagement: "Gestion de l'Inventaire",
    inventoryDescription: "Gérer le stock et les prix de toutes les cartes",
    totalCards: "Total Cartes",
    normalStock: "Stock Normal",
    foilStock: "Stock Foil",
    inventoryValue: "Valeur de l'Inventaire",
    searchInventory: "Rechercher par nom, numéro ou set...",
    stockStatus: "État du Stock",
    allStock: "Tout le Stock",
    allStockStatus: "Tous les États",
    inStock: "En Stock",
    lowStock: "Stock Faible",
    stockType: "Type de Stock",
    hasNormal: "A du Stock Normal",
    hasFoil: "A du Stock Foil",
    hasBoth: "A les Deux",
    all: "Tous",
    allTypes: "Tous les Types",
    allSets: "Tous les Sets",
    allRarities: "Toutes les Raretés",
    clearFilters: "Effacer les Filtres",
    showingCards: "Affichage",
    ofCards: "de",
    cards: "cartes",
    price: "Prix",
    foilPriceLabel: "Prix Foil",
    name: "Nom",
    cardNum: "Carte #",
    // Stock badges
    lowStockBadge: "Stock Faible",
    outOfStockBadge: "Rupture de Stock",
  },
  de: {
    home: "Startseite",
    catalog: "Katalog",
    news: "Neuigkeiten",
    contact: "Kontakt",
    search: "Nach Name oder Nummer suchen...",
    cart: "Warenkorb",
    heroTitle: "Finden Sie Ihre perfekte Lorcana-Karte",
    heroSubtitle: "Entdecken, filtern und sammeln Sie Ihre Lieblingskarten",
    browseCatalog: "Karten durchsuchen",
    // Home page features
    legendaryCards: "Legendäre Karten",
    legendaryCardsDesc: "Entdecken Sie seltene und legendäre Karten aus allen Lorcana-Sets",
    foilVariants: "Foil-Varianten",
    foilVariantsDesc: "Premium-Foil-Versionen mit atemberaubenden holografischen Effekten",
    advancedFilters: "Erweiterte Filter",
    advancedFiltersDesc: "Finden Sie genau das, was Sie brauchen, mit leistungsstarken Suchtools",
    filters: "Filter",
    type: "Typ",
    set: "Set / Sammlung",
    rarity: "Seltenheit",
    cardNumber: "Kartennummer",
    priceRange: "Preisspanne",
    version: "Version",
    versionAvailability: "Versionsverfügbarkeit",
    allVersions: "Alle Versionen",
    normalOnly: "Nur Normal",
    foilOnly: "Nur Foil",
    bothAvailable: "Beide Verfügbar",
    stockAvailability: "Bestandsverfügbarkeit",
    sortBy: "Sortieren nach",
    gridView: "Rasteransicht",
    listView: "Listenansicht",
    viewLabel: "Ansicht",
    addToCart: "In den Warenkorb",
    processing: "Verarbeitung...",
    cardUnavailable: "Diese Karte ist derzeit in keiner Version verfügbar.",
    goBack: "Zurück",
    normal: "Normal",
    foil: "Foil",
    character: "Charakter",
    item: "Gegenstand",
    action: "Aktion",
    song: "Lied",
    common: "Gewöhnlich",
    uncommon: "Ungewöhnlich",
    rare: "Selten",
    superRare: "Super Selten",
    legendary: "Legendär",
    enchanted: "Verzaubert",
    firstChapter: "Das Erste Kapitel",
    riseOfFloodborn: "Aufstieg der Floodborn",
    intoInklands: "In die Inklands",
    ursulaReturn: "Ursulas Rückkehr",
    shimmering: "Schimmernde Himmel",
    azurite: "Azuritsee",
    total: "Gesamt",
    checkout: "Zur Kasse",
    emptyCart: "Ihr Warenkorb ist leer",
    about: "Über uns",
    privacy: "Datenschutz",
    copyright: "© 2025 GA Company. Alle Rechte vorbehalten.",
    // Footer
    lorcanasingles: "Lorcana Singles",
    links: "Links",
    followUs: "Folgen Sie Uns",
    nameAZ: "Name (A-Z)",
    nameZA: "Name (Z-A)",
    priceLowHigh: "Preis (Niedrig bis Hoch)",
    priceHighLow: "Preis (Hoch bis Niedrig)",
    raritySort: "Seltenheit",
    cardNumberLowHigh: "Kartennummer (Niedrig bis Hoch)",
    cardNumberHighLow: "Kartennummer (Hoch bis Niedrig)",
    // Common UI
    viewStore: "Shop Ansehen",
    quantity: "Menge",
    loading: "Laden...",
    loadingSubmissions: "Einreichungen werden geladen...",
    loadingLogs: "Aktivitätsprotokolle werden geladen...",
    saving: "Speichern...",
    save: "Speichern",
    saveAll: "Alle Änderungen Speichern",
    cancel: "Abbrechen",
    edit: "Bearbeiten",
    delete: "Löschen",
    error: "Fehler",
    success: "Erfolg",
    buyNow: "Jetzt Kaufen",
    outOfStock: "Ausverkauft",
    each: "jeweils",
    approve: "Genehmigen",
    reject: "Ablehnen",
    approvePublish: "Genehmigen und Veröffentlichen",
    rejectSubmission: "Einreichung Ablehnen",
    // Orders
    orders: "Bestellungen",
    orderDetails: "Bestelldetails",
    ordersDescription: "Verwalten und überprüfen Sie alle im Shop aufgegebenen Bestellungen",
    customer: "Kunde",
    email: "E-Mail",
    customerName: "Name",
    paymentInfo: "Zahlungsinformationen",
    paymentId: "Zahlungs-ID",
    reference: "Referenz",
    paymentStatus: "Status",
    paymentMethod: "Methode",
    paidAt: "Bezahlt",
    products: "Produkte",
    quantity: "Menge",
    totalOrders: "Gesamt Bestellungen",
    totalRevenue: "Gesamterlös",
    productsSold: "Verkaufte Produkte",
    approvedOrders: "Genehmigte Bestellungen",
    soldCards: "Verkaufte Karten",
    searchOrders: "Suche nach E-Mail, Zahlungs-ID oder Referenz...",
    allOrders: "Alle Bestellungen",
    noOrders: "Noch keine Bestellungen",
    noOrdersFound: "Keine Bestellungen gefunden",
    loadingOrders: "Bestellungen werden geladen...",
    view: "Ansehen",
    date: "Datum",
    items: "Artikel",
    status: "Status",
    actions: "Aktionen",
    // Status
    approved: "Genehmigt",
    pending: "Ausstehend",
    rejected: "Abgelehnt",
    cancelled: "Storniert",
    refunded: "Erstattet",
    // Inventory
    inventoryManagement: "Bestandsverwaltung",
    inventoryDescription: "Verwalten Sie Lagerbestände und Preise aller Karten",
    totalCards: "Gesamt Karten",
    normalStock: "Normaler Bestand",
    foilStock: "Foil Bestand",
    inventoryValue: "Inventarwert",
    searchInventory: "Nach Name, Kartennummer oder Set suchen...",
    stockStatus: "Bestandsstatus",
    allStock: "Aller Bestand",
    allStockStatus: "Alle Status",
    inStock: "Auf Lager",
    lowStock: "Niedriger Bestand",
    stockType: "Bestandstyp",
    hasNormal: "Hat Normalen Bestand",
    hasFoil: "Hat Foil Bestand",
    hasBoth: "Hat Beide",
    all: "Alle",
    allTypes: "Alle Typen",
    allSets: "Alle Sets",
    allRarities: "Alle Seltenheiten",
    clearFilters: "Filter Löschen",
    showingCards: "Anzeige",
    ofCards: "von",
    cards: "karten",
    price: "Preis",
    foilPriceLabel: "Foil Preis",
    name: "Name",
    cardNum: "Karte #",
    // Stock badges
    lowStockBadge: "Niedriger Bestand",
    outOfStockBadge: "Ausverkauft",
  },
  es: {
    home: "Inicio",
    catalog: "Catálogo",
    news: "Noticias",
    contact: "Contacto",
    search: "Buscar por nombre o número...",
    cart: "Carrito",
    heroTitle: "Encuentra tu carta Lorcana perfecta",
    heroSubtitle: "Descubre, filtra y colecciona tus cartas favoritas",
    browseCatalog: "Explorar cartas",
    // Home page features
    legendaryCards: "Cartas Legendarias",
    legendaryCardsDesc: "Descubre cartas raras y legendarias de todos los sets de Lorcana",
    foilVariants: "Variantes Foil",
    foilVariantsDesc: "Versiones premium foil con efectos holográficos impresionantes",
    advancedFilters: "Filtros Avanzados",
    advancedFiltersDesc: "Encuentra exactamente lo que necesitas con herramientas de búsqueda potentes",
    filters: "Filtros",
    type: "Tipo",
    set: "Set / Colección",
    rarity: "Rareza",
    cardNumber: "Número de carta",
    priceRange: "Rango de precio",
    version: "Versión",
    versionAvailability: "Disponibilidad de Versión",
    allVersions: "Todas las Versiones",
    normalOnly: "Solo Normal",
    foilOnly: "Solo Foil",
    bothAvailable: "Ambas Disponibles",
    stockAvailability: "Disponibilidad de Stock",
    sortBy: "Ordenar por",
    gridView: "Vista de cuadrícula",
    listView: "Vista de lista",
    viewLabel: "Vista",
    addToCart: "Añadir al carrito",
    processing: "Procesando...",
    cardUnavailable: "Esta carta no está disponible actualmente en ninguna versión.",
    goBack: "Volver",
    normal: "Normal",
    foil: "Foil",
    character: "Personaje",
    item: "Objeto",
    action: "Acción",
    song: "Canción",
    common: "Común",
    uncommon: "Poco común",
    rare: "Raro",
    superRare: "Super Raro",
    legendary: "Legendario",
    enchanted: "Encantado",
    firstChapter: "El Primer Capítulo",
    riseOfFloodborn: "Ascenso de los Floodborn",
    intoInklands: "Hacia las Inklands",
    ursulaReturn: "El Regreso de Úrsula",
    shimmering: "Cielos Brillantes",
    azurite: "Mar Azurita",
    total: "Total",
    checkout: "Finalizar compra",
    emptyCart: "Tu carrito está vacío",
    about: "Acerca de",
    privacy: "Política de privacidad",
    copyright: "© 2025 GA Company. Todos los derechos reservados.",
    // Footer
    lorcanasingles: "Singles de Lorcana",
    links: "Enlaces",
    followUs: "Síguenos",
    nameAZ: "Nombre (A-Z)",
    nameZA: "Nombre (Z-A)",
    priceLowHigh: "Precio (Bajo a Alto)",
    priceHighLow: "Precio (Alto a Bajo)",
    raritySort: "Rareza",
    cardNumberLowHigh: "Número de Carta (Bajo a Alto)",
    cardNumberHighLow: "Número de Carta (Alto a Bajo)",
    // Common UI
    viewStore: "Ver Tienda",
    quantity: "Cantidad",
    loading: "Cargando...",
    loadingSubmissions: "Cargando envíos...",
    loadingLogs: "Cargando logs de actividad...",
    saving: "Guardando...",
    save: "Guardar",
    saveAll: "Guardar Todos los Cambios",
    cancel: "Cancelar",
    edit: "Editar",
    delete: "Eliminar",
    error: "Error",
    success: "Éxito",
    buyNow: "Comprar Ahora",
    outOfStock: "Sin Stock",
    each: "cada uno",
    approve: "Aprobar",
    reject: "Rechazar",
    approvePublish: "Aprobar y Publicar",
    rejectSubmission: "Rechazar Envío",
    // Orders
    orders: "Órdenes",
    orderDetails: "Detalles de la Orden",
    ordersDescription: "Gestiona y revisa todas las órdenes realizadas en la tienda",
    customer: "Cliente",
    email: "Email",
    customerName: "Nombre",
    paymentInfo: "Información de Pago",
    paymentId: "ID de Pago",
    reference: "Referencia",
    paymentStatus: "Estado",
    paymentMethod: "Método",
    paidAt: "Pagado",
    products: "Productos",
    quantity: "Cantidad",
    totalOrders: "Total Órdenes",
    totalRevenue: "Ingresos Totales",
    productsSold: "Productos Vendidos",
    approvedOrders: "Órdenes aprobadas",
    soldCards: "Cartas vendidas",
    searchOrders: "Buscar por email, payment ID o referencia...",
    allOrders: "Todas las Órdenes",
    noOrders: "No hay órdenes aún",
    noOrdersFound: "No se encontraron órdenes",
    loadingOrders: "Cargando órdenes...",
    view: "Ver",
    date: "Fecha",
    items: "Items",
    status: "Estado",
    actions: "Acciones",
    // Status
    approved: "Aprobado",
    pending: "Pendiente",
    rejected: "Rechazado",
    cancelled: "Cancelado",
    refunded: "Reembolsado",
    // Inventory
    inventoryManagement: "Gestión de Inventario",
    inventoryDescription: "Gestiona stock y precios de todas las cartas",
    totalCards: "Total Cartas",
    normalStock: "Stock Normal",
    foilStock: "Stock Foil",
    inventoryValue: "Valor del Inventario",
    searchInventory: "Buscar por nombre, número de carta o set...",
    stockStatus: "Estado de Stock",
    allStock: "Todo el Stock",
    allStockStatus: "Todos los Estados",
    inStock: "Con Stock",
    lowStock: "Stock Bajo",
    stockType: "Tipo de Stock",
    hasNormal: "Tiene Stock Normal",
    hasFoil: "Tiene Stock Foil",
    hasBoth: "Tiene Ambos",
    all: "Todos",
    allTypes: "Todos los Tipos",
    allSets: "Todos los Sets",
    allRarities: "Todas las Rarezas",
    clearFilters: "Limpiar Filtros",
    showingCards: "Mostrando",
    ofCards: "de",
    cards: "cartas",
    price: "Precio",
    foilPriceLabel: "Precio Foil",
    name: "Nombre",
    cardNum: "Carta #",
    // Stock badges
    lowStockBadge: "Stock Bajo",
    outOfStockBadge: "Sin Stock",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  useEffect(() => {
    // Auto-detect browser language
    const browserLang = navigator.language.split("-")[0] as Language
    if (["en", "fr", "de", "es"].includes(browserLang)) {
      setLanguage(browserLang)
    }
  }, [])

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}
