"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

type Language = "en" | "fr" | "de" | "es"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: "Home",
    catalog: "Catalog",
    news: "News",
    contact: "Contact",
    search: "Search by name or number...",
    cart: "Cart",
    heroTitle: "Find your perfect Lorcana card",
    heroSubtitle: "Discover, filter and collect your favorite cards",
    browseCatalog: "Browse Cards",
    filters: "Filters",
    type: "Type",
    set: "Set / Collection",
    rarity: "Rarity",
    cardNumber: "Card Number",
    priceRange: "Price Range",
    version: "Version",
    sortBy: "Sort By",
    gridView: "Grid View",
    listView: "List View",
    addToCart: "Add to Cart",
    goBack: "Go Back",
    normal: "Normal",
    foil: "Foil",
    character: "Character",
    item: "Item",
    action: "Action",
    song: "Song",
    common: "Common",
    uncommon: "Uncommon",
    rare: "Rare",
    superRare: "Super Rare",
    legendary: "Legendary",
    enchanted: "Enchanted",
    firstChapter: "The First Chapter",
    riseOfFloodborn: "Rise of the Floodborn",
    intoInklands: "Into the Inklands",
    ursulaReturn: "Ursula's Return",
    shimmering: "Shimmering Skies",
    azurite: "Azurite Sea",
    total: "Total",
    checkout: "Checkout",
    emptyCart: "Your cart is empty",
    about: "About",
    privacy: "Privacy Policy",
    copyright: "© 2025 Disney Lorcana. All rights reserved.",
    nameAZ: "Name (A-Z)",
    nameZA: "Name (Z-A)",
    priceLowHigh: "Price (Low to High)",
    priceHighLow: "Price (High to Low)",
    raritySort: "Rarity",
  },
  fr: {
    home: "Accueil",
    catalog: "Catalogue",
    news: "Actualités",
    contact: "Contact",
    search: "Rechercher par nom ou numéro...",
    cart: "Panier",
    heroTitle: "Trouvez votre carte Lorcana parfaite",
    heroSubtitle: "Découvrez, filtrez et collectionnez vos cartes préférées",
    browseCatalog: "Parcourir les cartes",
    filters: "Filtres",
    type: "Type",
    set: "Set / Collection",
    rarity: "Rareté",
    cardNumber: "Numéro de carte",
    priceRange: "Gamme de prix",
    version: "Version",
    sortBy: "Trier par",
    gridView: "Vue grille",
    listView: "Vue liste",
    addToCart: "Ajouter au panier",
    goBack: "Retour",
    normal: "Normal",
    foil: "Foil",
    character: "Personnage",
    item: "Objet",
    action: "Action",
    song: "Chanson",
    common: "Commun",
    uncommon: "Peu commun",
    rare: "Rare",
    superRare: "Super Rare",
    legendary: "Légendaire",
    enchanted: "Enchanté",
    firstChapter: "Le Premier Chapitre",
    riseOfFloodborn: "Montée des Floodborn",
    intoInklands: "Dans les Inklands",
    ursulaReturn: "Le Retour d'Ursula",
    shimmering: "Cieux Scintillants",
    azurite: "Mer Azurite",
    total: "Total",
    checkout: "Commander",
    emptyCart: "Votre panier est vide",
    about: "À propos",
    privacy: "Politique de confidentialité",
    copyright: "© 2025 Disney Lorcana. Tous droits réservés.",
    nameAZ: "Nom (A-Z)",
    nameZA: "Nom (Z-A)",
    priceLowHigh: "Prix (Bas à Élevé)",
    priceHighLow: "Prix (Élevé à Bas)",
    raritySort: "Rareté",
  },
  de: {
    home: "Startseite",
    catalog: "Katalog",
    news: "Neuigkeiten",
    contact: "Kontakt",
    search: "Nach Name oder Nummer suchen...",
    cart: "Warenkorb",
    heroTitle: "Finden Sie Ihre perfekte Lorcana-Karte",
    heroSubtitle: "Entdecken, filtern und sammeln Sie Ihre Lieblingskarten",
    browseCatalog: "Karten durchsuchen",
    filters: "Filter",
    type: "Typ",
    set: "Set / Sammlung",
    rarity: "Seltenheit",
    cardNumber: "Kartennummer",
    priceRange: "Preisspanne",
    version: "Version",
    sortBy: "Sortieren nach",
    gridView: "Rasteransicht",
    listView: "Listenansicht",
    addToCart: "In den Warenkorb",
    goBack: "Zurück",
    normal: "Normal",
    foil: "Foil",
    character: "Charakter",
    item: "Gegenstand",
    action: "Aktion",
    song: "Lied",
    common: "Gewöhnlich",
    uncommon: "Ungewöhnlich",
    rare: "Selten",
    superRare: "Super Selten",
    legendary: "Legendär",
    enchanted: "Verzaubert",
    firstChapter: "Das Erste Kapitel",
    riseOfFloodborn: "Aufstieg der Floodborn",
    intoInklands: "In die Inklands",
    ursulaReturn: "Ursulas Rückkehr",
    shimmering: "Schimmernde Himmel",
    azurite: "Azuritsee",
    total: "Gesamt",
    checkout: "Zur Kasse",
    emptyCart: "Ihr Warenkorb ist leer",
    about: "Über uns",
    privacy: "Datenschutz",
    copyright: "© 2025 Disney Lorcana. Alle Rechte vorbehalten.",
    nameAZ: "Name (A-Z)",
    nameZA: "Name (Z-A)",
    priceLowHigh: "Preis (Niedrig bis Hoch)",
    priceHighLow: "Preis (Hoch bis Niedrig)",
    raritySort: "Seltenheit",
  },
  es: {
    home: "Inicio",
    catalog: "Catálogo",
    news: "Noticias",
    contact: "Contacto",
    search: "Buscar por nombre o número...",
    cart: "Carrito",
    heroTitle: "Encuentra tu carta Lorcana perfecta",
    heroSubtitle: "Descubre, filtra y colecciona tus cartas favoritas",
    browseCatalog: "Explorar cartas",
    filters: "Filtros",
    type: "Tipo",
    set: "Set / Colección",
    rarity: "Rareza",
    cardNumber: "Número de carta",
    priceRange: "Rango de precio",
    version: "Versión",
    sortBy: "Ordenar por",
    gridView: "Vista de cuadrícula",
    listView: "Vista de lista",
    addToCart: "Añadir al carrito",
    goBack: "Volver",
    normal: "Normal",
    foil: "Foil",
    character: "Personaje",
    item: "Objeto",
    action: "Acción",
    song: "Canción",
    common: "Común",
    uncommon: "Poco común",
    rare: "Raro",
    superRare: "Super Raro",
    legendary: "Legendario",
    enchanted: "Encantado",
    firstChapter: "El Primer Capítulo",
    riseOfFloodborn: "Ascenso de los Floodborn",
    intoInklands: "Hacia las Inklands",
    ursulaReturn: "El Regreso de Úrsula",
    shimmering: "Cielos Brillantes",
    azurite: "Mar Azurita",
    total: "Total",
    checkout: "Finalizar compra",
    emptyCart: "Tu carrito está vacío",
    about: "Acerca de",
    privacy: "Política de privacidad",
    copyright: "© 2025 Disney Lorcana. Todos los derechos reservados.",
    nameAZ: "Nombre (A-Z)",
    nameZA: "Nombre (Z-A)",
    priceLowHigh: "Precio (Bajo a Alto)",
    priceHighLow: "Precio (Alto a Bajo)",
    raritySort: "Rareza",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  useEffect(() => {
    // Auto-detect browser language
    const browserLang = navigator.language.split("-")[0] as Language
    if (["en", "fr", "de", "es"].includes(browserLang)) {
      setLanguage(browserLang)
    }
  }, [])

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}
