"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

type Language = "en" | "fr" | "de" | "es"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: "Home",
    catalog: "Catalog",
    filtersAndSort: "Filters & Sort",
    loadingCards: "Loading cards...",
    loadingText: "Loading...",
    cardFound: "card",
    cardsFound: "cards",
    foundText: "found",
    noCardsFound: "No cards found matching your filters",
    noCardsSearch: "No cards found matching your search.",
    submitCardInstead: "Submit Your Card Instead",
    news: "News",
    contact: "Contact",
    search: "Search by name or number...",
    cart: "Cart",
    emptyCart: "Your cart is empty",
    checkout: "Checkout",
    total: "Total",
    minimumPurchase: "Minimum purchase amount is $50 CLP",
    checkoutError: "Failed to process checkout. Please try again.",
    toggleTheme: "Toggle theme",
    lightMode: "Light",
    darkMode: "Dark",
    systemMode: "System",
    heroTitle: "Find your perfect Lorcana card",
    heroSubtitle: "Discover, filter and collect your favorite cards",
    browseCatalog: "Browse Cards",
    // Guided Tour
    tourNavigation: "Here you can explore Lorcana products. Navigate through the catalog, products, and more.",
    tourCatalog: "Explore our complete catalog of Lorcana cards with updated prices.",
    tourLogin: "To save your cards and create collections, sign in here. It's free and quick.",
    tourCollection: "In 'My Collection' you'll see your saved cards, values, and personalized lists.",
    back: "Back",
    next: "Next",
    skip: "Skip",
    finish: "Finish",
    close: "Close",
    haveACard: "Have a Card to Sell?",
    haveACardDesc: "Submit your Lorcana cards to our catalog and we'll review them for inclusion in our store.",
    error: "Error",
    cancel: "Cancel",
    confirm: "Confirm",
    // Submit Card Form
    submitCard: "Submit a Card",
    submitCardDescription: "Have a card you'd like to add to our catalog? Submit it for review!",
    cardInformation: "Card Information",
    cardInformationDesc: "Fill in the details about the card you want to submit",
    cardName: "Card Name",
    cardNamePlaceholder: "e.g., Mickey Mouse - Brave Little Tailor",
    selectSet: "Select a set",
    selectType: "Select a type",
    selectRarity: "Select rarity",
    unknown: "Unknown / Other",
    description: "Description",
    descriptionPlaceholder: "Enter the card's abilities and description",
    imageUrl: "Image URL",
    imageUrlHelp: "Paste a link to the card's image (optional)",
    suggestedPrice: "Suggested Price (CLP)",
    suggestedPriceHelp: "Optional - What price do you think is fair?",
    contactEmail: "Contact Email",
    contactEmailHelp: "We'll notify you when your submission is reviewed",
    additionalNotes: "Additional Notes",
    additionalNotesPlaceholder: "Any extra information about the card...",
    submitting: "Submitting...",
    submissionSuccess: "Submission Received!",
    submissionSuccessDesc: "Thank you! Your card has been submitted for review.",
    submissionReviewMessage: "Our team will review your submission and you'll be notified by email.",
    submitAnother: "Submit Another Card",
    submissionError: "Failed to submit card. Please try again.",
    fillRequiredFields: "Please fill in all required fields",
    editSubmission: "Edit Submission",
    editSubmissionDesc: "Review and modify the card details before approving",
    preview: "Preview",
    previewDesc: "How the card will appear in the catalog",
    untitled: "Untitled Card",
    submittedBy: "Submitted by",
    submittedAt: "Submitted at",
    success: "Success",
    submissionUpdated: "Submission updated successfully",
    saveChanges: "Save Changes",
    // Home page features
    heroTitleWithProducts: "Lorcana Cards and Products in Chile",
    heroSubtitleWithProducts: "Individual cards and new sealed products. Everything 100% original and factory sealed.",
    categoriesAvailable: "Available Categories",
    individualCards: "Individual Cards",
    individualCardsDesc: "Loose cards of all rarities. Normal and foil versions available. Real-time stock updates.",
    sealedProducts: "New Sealed Products",
    sealedProductsDesc: "Boosters, playmats, sleeves, deck boxes and more. All our products are 100% original and factory sealed.",
    tcgAccessories: "TCG Accessories",
    tcgAccessoriesDesc: "Everything you need to play and protect your cards. Sleeves, deck boxes, dice and more premium accessories.",
    whyBuyFromUs: "Why Buy From Us",
    whyBuyFromUsDesc: "Updated stock, competitive prices and shipping throughout Chile. Your trusted store for Disney Lorcana cards and products.",
    sealedProductsHighlight: "100% Sealed and New Products",
    sealedProductsHighlightDesc: "All our sealed products (boosters, playmats, sleeves, etc.) are completely new and come factory sealed. We guarantee authenticity and quality with every purchase.",
    legendaryCards: "Legendary Cards",
    legendaryCardsDesc: "Discover rare and legendary cards from all Lorcana sets",
    foilVariants: "Foil Variants",
    foilVariantsDesc: "Premium foil versions with stunning holographic effects",
    advancedFilters: "Advanced Filters",
    advancedFiltersDesc: "Find exactly what you need with powerful search tools",
    filters: "Filters",
    type: "Type",
    set: "Set / Collection",
    rarity: "Rarity",
    cardNumber: "Card Number",
    language: "Language",
    priceRange: "Price Range",
    version: "Version",
    versionAvailability: "Version Availability",
    allVersions: "All Versions",
    normalOnly: "Normal Only",
    foilOnly: "Foil Only",
    bothAvailable: "Both Available",
    stockAvailability: "Stock Availability",
    sortBy: "Sort By",
    gridView: "Grid View",
    listView: "List View",
    viewLabel: "View",
    addToCart: "Add to Cart",
    processing: "Processing...",
    cardUnavailable: "This card is currently unavailable in all versions.",
    goBack: "Go Back",
    normal: "Normal",
    foil: "Foil",
    character: "Character",
    item: "Item",
    action: "Action",
    song: "Song",
    common: "Common",
    uncommon: "Uncommon",
    rare: "Rare",
    superRare: "Super Rare",
    legendary: "Legendary",
    enchanted: "Enchanted",
    firstChapter: "The First Chapter",
    riseOfFloodborn: "Rise of the Floodborn",
    intoInklands: "Into the Inklands",
    ursulaReturn: "Ursula's Return",
    shimmering: "Shimmering Skies",
    azurite: "Azurite Sea",
    archazia: "Archazia's Island",
    reignOfJafar: "Reign of Jafar",
    fabled: "Fabled",
    whispersInTheWell: "Whispers in the Well",
    total: "Total",
    checkout: "Checkout",
    emptyCart: "Your cart is empty",
    about: "About",
    privacy: "Privacy Policy",
    copyright: "© 2025 GA Company. All rights reserved.",
    // Footer
    lorcanasingles: "Lorcana Singles",
    links: "Links",
    followUs: "Follow Us",
    nameAZ: "Name (A-Z)",
    nameZA: "Name (Z-A)",
    priceLowHigh: "Price (Low to High)",
    priceHighLow: "Price (High to Low)",
    raritySort: "Rarity",
    cardNumberLowHigh: "Card Number (Low to High)",
    cardNumberHighLow: "Card Number (High to Low)",
    // Common UI
    viewStore: "View Store",
    quantity: "Quantity",
    loading: "Loading...",
    loadingSubmissions: "Loading submissions...",
    loadingLogs: "Loading activity logs...",
    saving: "Saving...",
    save: "Save",
    saveAll: "Save All Changes",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    error: "Error",
    success: "Success",
    buyNow: "Buy Now",
    outOfStock: "Out of Stock",
    each: "each",
    approve: "Approve",
    reject: "Reject",
    approvePublish: "Approve & Publish",
    rejectSubmission: "Reject Submission",
    // Orders
    orders: "Orders",
    orderDetails: "Order Details",
    ordersDescription: "Manage and review all orders placed in the store",
    customer: "Customer",
    email: "Email",
    customerName: "Name",
    paymentInfo: "Payment Information",
    paymentId: "Payment ID",
    reference: "Reference",
    paymentStatus: "Status",
    paymentMethod: "Method",
    paidAt: "Paid",
    products: "Products",
    quantity: "Quantity",
    totalOrders: "Total Orders",
    totalRevenue: "Total Revenue",
    grossRevenue: "Gross revenue",
    netRevenue: "Net Revenue",
    afterMPFees: "After Mercado Pago fees",
    productsSold: "Products Sold",
    approvedOrders: "Approved orders",
    soldCards: "Cards sold",
    searchOrders: "Search by email, payment ID or reference...",
    allOrders: "All Orders",
    noOrders: "No orders yet",
    noOrdersFound: "No orders found",
    loadingOrders: "Loading orders...",
    view: "View",
    date: "Date",
    items: "Items",
    status: "Status",
    // Admin Login
    password: "Password",
    emailPlaceholder: "admin@example.com",
    passwordPlaceholder: "••••••••",
    login: "Login",
    loggingIn: "Logging in...",
    loginNote: "If you don't have an admin account, contact the system administrator.",
    // Admin Submissions
    enterRejectionReason: "Enter rejection reason...",
    // Admin Inventory
    noChanges: "No changes",
    noStockChanges: "No stock changes to save",
    actions: "Actions",
    // Admin Tools
    tools: "Tools",
    adminTools: "Admin Tools",
    updateOrderFees: "Update Order Fees",
    processPayment: "Process Payment",
    inspectPayment: "Inspect Payment",
    // Status
    approved: "Approved",
    pending: "Pending",
    rejected: "Rejected",
    cancelled: "Cancelled",
    refunded: "Refunded",
    // Inventory
    inventoryManagement: "Inventory Management",
    inventoryDescription: "Manage stock and prices for all cards",
    importCards: "Import Cards from API",
    importing: "Importing...",
    totalCards: "Total Cards",
    normalStock: "Normal Stock",
    foilStock: "Foil Stock",
    inventoryValue: "Inventory Value",
    searchInventory: "Search by name, card number, or set...",
    stockStatus: "Stock Status",
    allStock: "All Stock",
    allStockStatus: "All Stock Status",
    inStock: "In Stock",
    lowStock: "Low Stock",
    stockType: "Stock Type",
    hasNormal: "Has Normal Stock",
    hasFoil: "Has Foil Stock",
    hasBoth: "Has Both",
    all: "All",
    allTypes: "All Types",
    allSets: "All Sets",
    allRarities: "All Rarities",
    clearFilters: "Clear Filters",
    showingCards: "Showing",
    ofCards: "of",
    cards: "cards",
    price: "Price",
    foilPriceLabel: "Foil Price",
    name: "Name",
    cardNum: "Card #",
    // Stock badges
    lowStockBadge: "Low Stock",
    outOfStockBadge: "Out of Stock",
    // Public Login
    signIn: "Sign In",
    signInWith: "Continue with",
    google: "Google",
    signInToSubmit: "Sign in to submit cards",
    signInRequired: "Sign in required",
    signInRequiredDesc: "Create an account or sign in to submit card proposals to our catalog.",
    createAccount: "Create Account",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    signUp: "Sign Up",
    welcomeBack: "Welcome back!",
    welcomeMessage: "Sign in with your Google account to continue",
    noAccountNeeded: "No account needed - your Google account is all you need",
    // My Submissions
    mySubmissions: "My Submissions",
    mySubmissionsDesc: "Manage your submitted card proposals",
    noSubmissions: "You haven't submitted any cards yet",
    noSubmissionsDesc: "When you submit cards to sell, they will appear here",
    submissionDetails: "Submission Details",
    viewDetails: "View Details",
    submissionStatus: "Submission Status",
    statusPending: "Pending review",
    statusApproved: "Approved - Added to catalog",
    statusRejected: "Rejected",
    rejectionReason: "Rejection reason",
    submittedOn: "Submitted on",
    reviewedOn: "Reviewed on",
    // User Menu
    myAccount: "My Account",
    myProfile: "My Profile",
    signOut: "Sign Out",
    adminPanel: "Admin Panel",
    // User Management
    userManagement: "User Management",
    userManagementDesc: "Manage user roles and permissions",
    allUsers: "All Users",
    totalUsers: "Total Users",
    adminUsers: "Admins",
    regularUsers: "Regular Users",
    searchUsers: "Search by name or email...",
    userEmail: "Email",
    userName: "Name",
    userRole: "Role",
    userSince: "Registered",
    lastLogin: "Last Login",
    makeAdmin: "Make Admin",
    removeAdmin: "Remove Admin",
    confirmMakeAdmin: "Are you sure you want to make this user an admin?",
    confirmRemoveAdmin: "Are you sure you want to remove admin privileges from this user?",
    adminRoleAssigned: "Admin role assigned successfully",
    adminRoleRemoved: "Admin role removed successfully",
    temporaryPassword: "Temporary Password",
    sharePasswordWithUser: "Share this password with the user so they can login with email/password. They can also continue using Google OAuth.",
    userCanAlsoUseOAuth: "Note: The user can also login using Google OAuth (no password needed).",
    copy: "Copy",
    copied: "Copied!",
    passwordCopied: "Password copied to clipboard",
    close: "Close",
    cannotRemoveSelf: "You cannot remove your own admin role",
    noUsersFound: "No users found",
    admin: "Admin",
    user: "User",
    // Auth Required Messages
    loginToView: "Sign in to view this page",
    loginToContinue: "Sign in to continue",
    authenticationRequired: "Authentication required",
    // My Collection
    myCollection: "My Collection",
    myCollectionDesc: "Track your Lorcana card collection and wishlist",
    owned: "I Own",
    wanted: "I Want",
    ownedCards: "Cards I Own",
    wantedCards: "Cards I Want",
    noOwnedCards: "You don't have any cards in your collection yet",
    noWantedCards: "You don't have any cards in your wishlist yet",
    addToCollection: "Add to Collection",
    removeFromCollection: "Remove from Collection",
    addToOwned: "I Have This",
    addToWanted: "I Want This",
    removeFromOwned: "Remove from Owned",
    removeFromWanted: "Remove from Wanted",
    alreadyOwned: "Already in collection",
    alreadyWanted: "Already in wishlist",
    addedToCollection: "Added to your collection",
    addedToWishlist: "Added to your wishlist",
    removedFromCollection: "Removed from your collection",
    addedToCart: "added to cart",
    removedFromWishlist: "Removed from your wishlist",
    collectionStats: "Collection Stats",
    totalOwned: "Total Cards Owned",
    totalWanted: "Total Cards Wanted",
    collectionValue: "Collection Value",
    mostWanted: "Most Wanted",
    recentlyAdded: "Recently Added",
    viewInCatalog: "View in Catalog",
    markAsOwned: "Mark as Owned",
    markAsWanted: "Mark as Wanted",
    quantity: "Quantity",
    updateQuantity: "Update Quantity",
    addNotes: "Add Notes",
    cardNotes: "Notes",
    notesPlaceholder: "Card condition, language, special features...",
    allCards: "All Cards",
    allCardsDesc: "Browse all cards and add to your collection",
    normal: "Normal",
    foil: "Foil",
    addNormal: "Add Normal",
    addFoil: "Add Foil",
    increaseQuantity: "Increase quantity",
    decreaseQuantity: "Decrease quantity",
    missingCards: "Missing Cards",
    missingCardsDesc: "Cards you don't have in your collection yet",
    noMissingCards: "You have all cards!",
    totalMissing: "Total Missing",
    // Shipping
    shippingMethod: "Shipping Method",
    shippingAddress: "Shipping Address",
    shippingZone: "Shipping Zone",
    shippingCost: "Shipping Cost",
    freeShipping: "FREE SHIPPING",
    freeShippingInfo: "Add to unlock free shipping",
    estimatedDelivery: "Estimated delivery",
    businessDays: "business days",
    street: "Street",
    number: "Number",
    commune: "Commune",
    city: "City",
    region: "Region",
    postalCode: "Postal Code",
    optional: "Optional",
    deliveryNotes: "Delivery Notes",
    free: "FREE",
    subtotal: "Subtotal",
    inCart: "in cart",
    available: "available",
    maxStockReached: "Maximum stock in cart",
    // Payment Section
    securePayment: "100% Secure Payment",
    securePaymentDesc: "We accept all payment methods through Mercado Pago",
    certifiedDeveloper: "Certified Developer",
    mercadoPagoCheckoutPro: "Mercado Pago Checkout Pro",
    acceptedPaymentMethods: "Accepted payment methods:",
    creditDebitCards: "💳 Credit and debit cards",
    bankTransfer: "🏦 Bank transfer",
    mercadoPagoBalance: "📱 Mercado Pago balance",
    // Products Page
    productsTitle: "Lorcana Products",
    productsSubtitle: "Boosters, Play Mats, Sleeves, Deck Boxes and more",
    productFound: "product found",
    productsFound: "products found",
    viewProducts: "View Products",
    productNotFound: "The product you're looking for doesn't exist.",
    productNotFoundTitle: "Product Not Found",
    productUnavailable: "This product is currently unavailable.",
    securePaymentWithMP: "100% secure payment with Mercado Pago",
    paymentMethodsShort: "Credit cards, debit cards and bank transfer",
    // Contact Page
    contactAndHours: "Contact and Business Hours",
    contactSubtitle: "Do you have any questions? We're here to help you",
    contactMethods: "Contact Methods",
    emailDescription: "Write to us for any inquiry",
    phoneDescription: "Call us or send us a WhatsApp",
    businessHours: "Business Hours",
    hoursWeekday: "Monday to Saturday: 10:00 AM - 8:00 PM",
    hoursWeekend: "Sunday: Closed",
    phone: "Phone",
    // Catalog Page
    cardTypes: "Card Types",
    unitAvailable: "unit available",
    unitsAvailable: "units available",
  },
  fr: {
    home: "Accueil",
    catalog: "Catalogue",
    filtersAndSort: "Filtres et Tri",
    loadingCards: "Chargement des cartes...",
    loadingText: "Chargement...",
    cardFound: "carte",
    cardsFound: "cartes",
    foundText: "trouvées",
    noCardsFound: "Aucune carte trouvée correspondant à vos filtres",
    noCardsSearch: "Aucune carte trouvée correspondant à votre recherche.",
    news: "Actualités",
    contact: "Contact",
    search: "Rechercher par nom ou numéro...",
    cart: "Panier",
    heroTitle: "Trouvez votre carte Lorcana parfaite",
    heroSubtitle: "Découvrez, filtrez et collectionnez vos cartes préférées",
    browseCatalog: "Parcourir les cartes",
    // Guided Tour
    tourNavigation: "Ici, vous pouvez explorer les produits Lorcana. Naviguez dans le catalogue, les produits et plus encore.",
    tourCatalog: "Explorez notre catalogue complet de cartes Lorcana avec des prix à jour.",
    tourLogin: "Pour sauvegarder vos cartes et créer des collections, connectez-vous ici. C'est gratuit et rapide.",
    tourCollection: "Dans 'Ma Collection', vous verrez vos cartes sauvegardées, valeurs et listes personnalisées.",
    back: "Retour",
    next: "Suivant",
    skip: "Passer",
    finish: "Terminer",
    close: "Fermer",
    // Home page features
    heroTitleWithProducts: "Cartes et Produits Lorcana au Chili",
    heroSubtitleWithProducts: "Cartes individuelles et produits scellés neufs. Tout 100% original et scellé d'usine.",
    categoriesAvailable: "Catégories Disponibles",
    individualCards: "Cartes Individuelles",
    individualCardsDesc: "Cartes à l'unité de toutes les raretés. Versions normale et foil disponibles. Stock mis à jour en temps réel.",
    sealedProducts: "Produits Scellés Neufs",
    sealedProductsDesc: "Boosters, tapis de jeu, protège-cartes, boîtes de deck et plus encore. Tous nos produits sont 100% originaux et scellés d'usine.",
    tcgAccessories: "Accessoires TCG",
    tcgAccessoriesDesc: "Tout ce dont vous avez besoin pour jouer et protéger vos cartes. Protège-cartes, boîtes de deck, dés et plus d'accessoires premium.",
    whyBuyFromUs: "Pourquoi Acheter Chez Nous",
    whyBuyFromUsDesc: "Stock à jour, prix compétitifs et livraison dans tout le Chili. Votre magasin de confiance pour les cartes et produits Disney Lorcana.",
    sealedProductsHighlight: "Produits 100% Scellés et Neufs",
    sealedProductsHighlightDesc: "Tous nos produits scellés (boosters, tapis de jeu, protège-cartes, etc.) sont complètement neufs et viennent scellés d'usine. Nous garantissons l'authenticité et la qualité à chaque achat.",
    legendaryCards: "Cartes Légendaires",
    legendaryCardsDesc: "Découvrez des cartes rares et légendaires de tous les sets Lorcana",
    foilVariants: "Variantes Foil",
    foilVariantsDesc: "Versions premium foil avec des effets holographiques époustouflants",
    advancedFilters: "Filtres Avancés",
    advancedFiltersDesc: "Trouvez exactement ce dont vous avez besoin avec des outils de recherche puissants",
    filters: "Filtres",
    type: "Type",
    set: "Set / Collection",
    rarity: "Rareté",
    cardNumber: "Numéro de carte",
    priceRange: "Gamme de prix",
    version: "Version",
    versionAvailability: "Disponibilité de Version",
    allVersions: "Toutes les Versions",
    normalOnly: "Normal Uniquement",
    foilOnly: "Foil Uniquement",
    bothAvailable: "Les Deux Disponibles",
    stockAvailability: "Disponibilité du Stock",
    sortBy: "Trier par",
    gridView: "Vue grille",
    listView: "Vue liste",
    viewLabel: "Vue",
    addToCart: "Ajouter au panier",
    processing: "Traitement...",
    cardUnavailable: "Cette carte n'est actuellement disponible dans aucune version.",
    goBack: "Retour",
    normal: "Normal",
    foil: "Foil",
    character: "Personnage",
    item: "Objet",
    action: "Action",
    song: "Chanson",
    common: "Commun",
    uncommon: "Peu commun",
    rare: "Rare",
    superRare: "Super Rare",
    legendary: "Légendaire",
    enchanted: "Enchanté",
    firstChapter: "Le Premier Chapitre",
    riseOfFloodborn: "Montée des Floodborn",
    intoInklands: "Dans les Inklands",
    ursulaReturn: "Le Retour d'Ursula",
    shimmering: "Cieux Scintillants",
    azurite: "Mer Azurite",
    archazia: "L'Île d'Archazia",
    reignOfJafar: "Règne de Jafar",
    fabled: "Fabled",
    whispersInTheWell: "Whispers in the Well",
    total: "Total",
    checkout: "Commander",
    emptyCart: "Votre panier est vide",
    about: "À propos",
    privacy: "Politique de confidentialité",
    copyright: "© 2025 GA Company. Tous droits réservés.",
    // Footer
    lorcanasingles: "Singles Lorcana",
    links: "Liens",
    followUs: "Suivez-Nous",
    nameAZ: "Nom (A-Z)",
    nameZA: "Nom (Z-A)",
    priceLowHigh: "Prix (Bas à Élevé)",
    priceHighLow: "Prix (Élevé à Bas)",
    raritySort: "Rareté",
    cardNumberLowHigh: "Numéro de Carte (Bas à Élevé)",
    cardNumberHighLow: "Numéro de Carte (Élevé à Bas)",
    // Common UI
    viewStore: "Voir la Boutique",
    quantity: "Quantité",
    loading: "Chargement...",
    loadingSubmissions: "Chargement des soumissions...",
    loadingLogs: "Chargement des logs d'activité...",
    saving: "Enregistrement...",
    save: "Enregistrer",
    saveAll: "Enregistrer Tous les Changements",
    cancel: "Annuler",
    confirm: "Confirmer",
    edit: "Modifier",
    delete: "Supprimer",
    error: "Erreur",
    success: "Succès",
    buyNow: "Acheter Maintenant",
    outOfStock: "Rupture de Stock",
    each: "chacun",
    approve: "Approuver",
    reject: "Rejeter",
    approvePublish: "Approuver et Publier",
    rejectSubmission: "Rejeter la Soumission",
    // Orders
    orders: "Commandes",
    orderDetails: "Détails de la Commande",
    ordersDescription: "Gérer et examiner toutes les commandes passées dans la boutique",
    customer: "Client",
    email: "Email",
    customerName: "Nom",
    paymentInfo: "Informations de Paiement",
    paymentId: "ID de Paiement",
    reference: "Référence",
    paymentStatus: "Statut",
    paymentMethod: "Méthode",
    paidAt: "Payé",
    products: "Produits",
    quantity: "Quantité",
    totalOrders: "Total Commandes",
    totalRevenue: "Revenus Totaux",
    grossRevenue: "Revenus bruts",
    netRevenue: "Revenus Nets",
    afterMPFees: "Après les frais de Mercado Pago",
    productsSold: "Produits Vendus",
    approvedOrders: "Commandes approuvées",
    soldCards: "Cartes vendues",
    searchOrders: "Rechercher par email, ID de paiement ou référence...",
    allOrders: "Toutes les Commandes",
    noOrders: "Pas encore de commandes",
    noOrdersFound: "Aucune commande trouvée",
    loadingOrders: "Chargement des commandes...",
    view: "Voir",
    date: "Date",
    items: "Articles",
    status: "Statut",
    // Admin Login
    password: "Mot de passe",
    emailPlaceholder: "admin@exemple.com",
    passwordPlaceholder: "••••••••",
    login: "Connexion",
    loggingIn: "Connexion en cours...",
    loginNote: "Si vous n'avez pas de compte admin, contactez l'administrateur système.",
    // Admin Submissions
    enterRejectionReason: "Entrez la raison du rejet...",
    // Admin Inventory
    noChanges: "Aucun changement",
    noStockChanges: "Aucun changement de stock à enregistrer",
    actions: "Actions",
    // Status
    approved: "Approuvé",
    pending: "En Attente",
    rejected: "Rejeté",
    cancelled: "Annulé",
    refunded: "Remboursé",
    // Inventory
    inventoryManagement: "Gestion de l'Inventaire",
    inventoryDescription: "Gérer le stock et les prix de toutes les cartes",
    importCards: "Importer des Cartes depuis l'API",
    importing: "Importation...",
    totalCards: "Total Cartes",
    normalStock: "Stock Normal",
    foilStock: "Stock Foil",
    inventoryValue: "Valeur de l'Inventaire",
    searchInventory: "Rechercher par nom, numéro ou set...",
    stockStatus: "État du Stock",
    allStock: "Tout le Stock",
    allStockStatus: "Tous les États",
    inStock: "En Stock",
    lowStock: "Stock Faible",
    stockType: "Type de Stock",
    hasNormal: "A du Stock Normal",
    hasFoil: "A du Stock Foil",
    hasBoth: "A les Deux",
    all: "Tous",
    allTypes: "Tous les Types",
    allSets: "Tous les Sets",
    allRarities: "Toutes les Raretés",
    clearFilters: "Effacer les Filtres",
    showingCards: "Affichage",
    ofCards: "de",
    cards: "cartes",
    price: "Prix",
    foilPriceLabel: "Prix Foil",
    name: "Nom",
    cardNum: "Carte #",
    // Stock badges
    lowStockBadge: "Stock Faible",
    outOfStockBadge: "Rupture de Stock",
    // Public Login
    signIn: "Se Connecter",
    signInWith: "Continuer avec",
    google: "Google",
    signInToSubmit: "Connectez-vous pour soumettre des cartes",
    signInRequired: "Connexion requise",
    signInRequiredDesc: "Créez un compte ou connectez-vous pour soumettre des propositions de cartes à notre catalogue.",
    createAccount: "Créer un Compte",
    alreadyHaveAccount: "Vous avez déjà un compte?",
    dontHaveAccount: "Vous n'avez pas de compte?",
    signUp: "S'inscrire",
    welcomeBack: "Bienvenue!",
    welcomeMessage: "Connectez-vous avec votre compte Google pour continuer",
    noAccountNeeded: "Aucun compte requis - votre compte Google suffit",
    // My Submissions
    mySubmissions: "Mes Soumissions",
    mySubmissionsDesc: "Gérez vos propositions de cartes soumises",
    noSubmissions: "Vous n'avez encore soumis aucune carte",
    noSubmissionsDesc: "Lorsque vous soumettez des cartes à vendre, elles apparaîtront ici",
    submissionDetails: "Détails de la Soumission",
    viewDetails: "Voir les Détails",
    submissionStatus: "Statut de la Soumission",
    statusPending: "En attente d'examen",
    statusApproved: "Approuvée - Ajoutée au catalogue",
    statusRejected: "Rejetée",
    rejectionReason: "Raison du rejet",
    submittedOn: "Soumis le",
    reviewedOn: "Examiné le",
    // User Menu
    myAccount: "Mon Compte",
    myProfile: "Mon Profil",
    signOut: "Déconnexion",
    adminPanel: "Panneau d'Admin",
    // User Management
    userManagement: "Gestion des Utilisateurs",
    userManagementDesc: "Gérer les rôles et permissions des utilisateurs",
    allUsers: "Tous les Utilisateurs",
    totalUsers: "Total Utilisateurs",
    adminUsers: "Admins",
    regularUsers: "Utilisateurs Réguliers",
    searchUsers: "Rechercher par nom ou email...",
    userEmail: "Email",
    userName: "Nom",
    userRole: "Rôle",
    userSince: "Inscrit",
    lastLogin: "Dernière Connexion",
    makeAdmin: "Rendre Admin",
    removeAdmin: "Retirer Admin",
    confirmMakeAdmin: "Êtes-vous sûr de vouloir rendre cet utilisateur admin?",
    confirmRemoveAdmin: "Êtes-vous sûr de vouloir retirer les privilèges admin de cet utilisateur?",
    adminRoleAssigned: "Rôle admin attribué avec succès",
    adminRoleRemoved: "Rôle admin retiré avec succès",
    temporaryPassword: "Mot de passe temporaire",
    sharePasswordWithUser: "Partagez ce mot de passe avec l'utilisateur pour qu'il puisse se connecter avec email/mot de passe. Il peut aussi continuer à utiliser Google OAuth.",
    userCanAlsoUseOAuth: "Note: L'utilisateur peut aussi se connecter avec Google OAuth (pas de mot de passe requis).",
    copy: "Copier",
    copied: "Copié!",
    passwordCopied: "Mot de passe copié dans le presse-papiers",
    close: "Fermer",
    cannotRemoveSelf: "Vous ne pouvez pas retirer votre propre rôle admin",
    noUsersFound: "Aucun utilisateur trouvé",
    admin: "Admin",
    user: "Utilisateur",
    // Auth Required Messages
    loginToView: "Connectez-vous pour voir cette page",
    loginToContinue: "Connectez-vous pour continuer",
    authenticationRequired: "Authentification requise",
    // My Collection
    myCollection: "Ma Collection",
    myCollectionDesc: "Suivez votre collection de cartes Lorcana et votre liste de souhaits",
    owned: "Je Possède",
    wanted: "Je Veux",
    ownedCards: "Cartes que Je Possède",
    wantedCards: "Cartes que Je Veux",
    noOwnedCards: "Vous n'avez encore aucune carte dans votre collection",
    noWantedCards: "Vous n'avez aucune carte dans votre liste de souhaits",
    addToCollection: "Ajouter à la Collection",
    removeFromCollection: "Retirer de la Collection",
    addToOwned: "Je l'ai",
    addToWanted: "Je la Veux",
    removeFromOwned: "Retirer des Possédées",
    removeFromWanted: "Retirer des Souhaitées",
    alreadyOwned: "Déjà dans la collection",
    alreadyWanted: "Déjà dans la liste de souhaits",
    addedToCollection: "Ajoutée à votre collection",
    addedToWishlist: "Ajoutée à votre liste de souhaits",
    removedFromCollection: "Retirée de votre collection",
    addedToCart: "ajoutée au panier",
    removedFromWishlist: "Retirée de votre liste de souhaits",
    collectionStats: "Statistiques de Collection",
    totalOwned: "Total de Cartes Possédées",
    totalWanted: "Total de Cartes Souhaitées",
    collectionValue: "Valeur de la Collection",
    mostWanted: "Plus Recherchées",
    recentlyAdded: "Récemment Ajoutées",
    viewInCatalog: "Voir dans le Catalogue",
    markAsOwned: "Marquer comme Possédée",
    markAsWanted: "Marquer comme Souhaitée",
    quantity: "Quantité",
    updateQuantity: "Mettre à Jour la Quantité",
    addNotes: "Ajouter des Notes",
    cardNotes: "Notes",
    notesPlaceholder: "État de la carte, langue, caractéristiques spéciales...",
    allCards: "Toutes les Cartes",
    allCardsDesc: "Parcourir toutes les cartes et ajouter à votre collection",
    normal: "Normal",
    foil: "Foil",
    addNormal: "Ajouter Normal",
    addFoil: "Ajouter Foil",
    increaseQuantity: "Augmenter la quantité",
    decreaseQuantity: "Diminuer la quantité",
    missingCards: "Cartes Manquantes",
    missingCardsDesc: "Cartes que vous n'avez pas encore dans votre collection",
    noMissingCards: "Vous avez toutes les cartes!",
    totalMissing: "Total Manquantes",
    // Shipping
    shippingMethod: "Méthode de Livraison",
    shippingAddress: "Adresse de Livraison",
    shippingZone: "Zone de Livraison",
    shippingCost: "Frais de Livraison",
    freeShipping: "LIVRAISON GRATUITE",
    freeShippingInfo: "Ajoutez pour débloquer la livraison gratuite",
    estimatedDelivery: "Livraison estimée",
    businessDays: "jours ouvrables",
    street: "Rue",
    number: "Numéro",
    commune: "Commune",
    city: "Ville",
    region: "Région",
    postalCode: "Code Postal",
    optional: "Optionnel",
    deliveryNotes: "Notes de Livraison",
    free: "GRATUIT",
    subtotal: "Sous-total",
    inCart: "dans le panier",
    available: "disponible",
    maxStockReached: "Stock maximum dans le panier",
    // Payment Section
    securePayment: "Paiement 100% Sécurisé",
    securePaymentDesc: "Nous acceptons tous les modes de paiement via Mercado Pago",
    certifiedDeveloper: "Développeur Certifié",
    mercadoPagoCheckoutPro: "Mercado Pago Checkout Pro",
    acceptedPaymentMethods: "Modes de paiement acceptés:",
    creditDebitCards: "💳 Cartes de crédit et de débit",
    bankTransfer: "🏦 Virement bancaire",
    mercadoPagoBalance: "📱 Solde Mercado Pago",
    // Products Page
    productsTitle: "Produits Lorcana",
    productsSubtitle: "Boosters, Tapis de Jeu, Protège-Cartes, Boîtes de Deck et plus",
    productFound: "produit trouvé",
    productsFound: "produits trouvés",
    viewProducts: "Voir les Produits",
    productNotFound: "Le produit que vous recherchez n'existe pas.",
    productNotFoundTitle: "Produit Non Trouvé",
    productUnavailable: "Ce produit n'est actuellement pas disponible.",
    securePaymentWithMP: "Paiement 100% sécurisé avec Mercado Pago",
    paymentMethodsShort: "Cartes de crédit, cartes de débit et virement bancaire",
    // Contact Page
    contactAndHours: "Contact et Heures d'Ouverture",
    contactSubtitle: "Avez-vous des questions? Nous sommes là pour vous aider",
    contactMethods: "Moyens de Contact",
    emailDescription: "Écrivez-nous pour toute demande",
    phoneDescription: "Appelez-nous ou envoyez-nous un WhatsApp",
    businessHours: "Heures d'Ouverture",
    hoursWeekday: "Lundi au Samedi: 10h00 - 20h00",
    hoursWeekend: "Dimanche: Fermé",
    phone: "Téléphone",
    // Catalog Page
    cardTypes: "Types de Cartes",
    unitAvailable: "unité disponible",
    unitsAvailable: "unités disponibles",
  },
  de: {
    home: "Startseite",
    catalog: "Katalog",
    filtersAndSort: "Filter & Sortierung",
    loadingCards: "Karten werden geladen...",
    loadingText: "Laden...",
    cardFound: "Karte",
    cardsFound: "Karten",
    foundText: "gefunden",
    noCardsFound: "Keine Karten gefunden, die Ihren Filtern entsprechen",
    noCardsSearch: "Keine Karten gefunden, die Ihrer Suche entsprechen.",
    news: "Neuigkeiten",
    contact: "Kontakt",
    search: "Nach Name oder Nummer suchen...",
    cart: "Warenkorb",
    heroTitle: "Finden Sie Ihre perfekte Lorcana-Karte",
    heroSubtitle: "Entdecken, filtern und sammeln Sie Ihre Lieblingskarten",
    browseCatalog: "Karten durchsuchen",
    // Guided Tour
    tourNavigation: "Hier können Sie Lorcana-Produkte erkunden. Navigieren Sie durch den Katalog, Produkte und mehr.",
    tourCatalog: "Erkunden Sie unseren vollständigen Katalog von Lorcana-Karten mit aktualisierten Preisen.",
    tourLogin: "Um Ihre Karten zu speichern und Sammlungen zu erstellen, melden Sie sich hier an. Es ist kostenlos und schnell.",
    tourCollection: "In 'Meine Sammlung' sehen Sie Ihre gespeicherten Karten, Werte und personalisierte Listen.",
    back: "Zurück",
    next: "Weiter",
    skip: "Überspringen",
    finish: "Beenden",
    close: "Schließen",
    // Home page features
    heroTitleWithProducts: "Lorcana Karten und Produkte in Chile",
    heroSubtitleWithProducts: "Einzelkarten und neue versiegelte Produkte. Alles 100% original und werksversiegelt.",
    categoriesAvailable: "Verfügbare Kategorien",
    individualCards: "Einzelkarten",
    individualCardsDesc: "Lose Karten aller Seltenheitsstufen. Normal- und Foil-Versionen verfügbar. Echtzeit-Bestandsaktualisierungen.",
    sealedProducts: "Neue Versiegelte Produkte",
    sealedProductsDesc: "Booster, Spielmatten, Hüllen, Deckboxen und mehr. Alle unsere Produkte sind 100% original und werksversiegelt.",
    tcgAccessories: "TCG-Zubehör",
    tcgAccessoriesDesc: "Alles was Sie zum Spielen und zum Schutz Ihrer Karten benötigen. Hüllen, Deckboxen, Würfel und mehr Premium-Zubehör.",
    whyBuyFromUs: "Warum Bei Uns Kaufen",
    whyBuyFromUsDesc: "Aktualisierter Bestand, wettbewerbsfähige Preise und Versand in ganz Chile. Ihr vertrauenswürdiger Shop für Disney Lorcana Karten und Produkte.",
    sealedProductsHighlight: "100% Versiegelte und Neue Produkte",
    sealedProductsHighlightDesc: "Alle unsere versiegelten Produkte (Booster, Spielmatten, Hüllen usw.) sind komplett neu und kommen werksversiegelt. Wir garantieren Authentizität und Qualität bei jedem Kauf.",
    legendaryCards: "Legendäre Karten",
    legendaryCardsDesc: "Entdecken Sie seltene und legendäre Karten aus allen Lorcana-Sets",
    foilVariants: "Foil-Varianten",
    foilVariantsDesc: "Premium-Foil-Versionen mit atemberaubenden holografischen Effekten",
    advancedFilters: "Erweiterte Filter",
    advancedFiltersDesc: "Finden Sie genau das, was Sie brauchen, mit leistungsstarken Suchtools",
    filters: "Filter",
    type: "Typ",
    set: "Set / Sammlung",
    rarity: "Seltenheit",
    cardNumber: "Kartennummer",
    priceRange: "Preisspanne",
    version: "Version",
    versionAvailability: "Versionsverfügbarkeit",
    allVersions: "Alle Versionen",
    normalOnly: "Nur Normal",
    foilOnly: "Nur Foil",
    bothAvailable: "Beide Verfügbar",
    stockAvailability: "Bestandsverfügbarkeit",
    sortBy: "Sortieren nach",
    gridView: "Rasteransicht",
    listView: "Listenansicht",
    viewLabel: "Ansicht",
    addToCart: "In den Warenkorb",
    processing: "Verarbeitung...",
    cardUnavailable: "Diese Karte ist derzeit in keiner Version verfügbar.",
    goBack: "Zurück",
    normal: "Normal",
    foil: "Foil",
    character: "Charakter",
    item: "Gegenstand",
    action: "Aktion",
    song: "Lied",
    common: "Gewöhnlich",
    uncommon: "Ungewöhnlich",
    rare: "Selten",
    superRare: "Super Selten",
    legendary: "Legendär",
    enchanted: "Verzaubert",
    firstChapter: "Das Erste Kapitel",
    riseOfFloodborn: "Aufstieg der Floodborn",
    intoInklands: "In die Inklands",
    ursulaReturn: "Ursulas Rückkehr",
    shimmering: "Schimmernde Himmel",
    azurite: "Azuritsee",
    archazia: "Archazias Insel",
    reignOfJafar: "Jafars Herrschaft",
    fabled: "Fabled",
    whispersInTheWell: "Whispers in the Well",
    total: "Gesamt",
    checkout: "Zur Kasse",
    emptyCart: "Ihr Warenkorb ist leer",
    about: "Über uns",
    privacy: "Datenschutz",
    copyright: "© 2025 GA Company. Alle Rechte vorbehalten.",
    // Footer
    lorcanasingles: "Lorcana Singles",
    links: "Links",
    followUs: "Folgen Sie Uns",
    nameAZ: "Name (A-Z)",
    nameZA: "Name (Z-A)",
    priceLowHigh: "Preis (Niedrig bis Hoch)",
    priceHighLow: "Preis (Hoch bis Niedrig)",
    raritySort: "Seltenheit",
    cardNumberLowHigh: "Kartennummer (Niedrig bis Hoch)",
    cardNumberHighLow: "Kartennummer (Hoch bis Niedrig)",
    // Common UI
    viewStore: "Shop Ansehen",
    quantity: "Menge",
    loading: "Laden...",
    loadingSubmissions: "Einreichungen werden geladen...",
    loadingLogs: "Aktivitätsprotokolle werden geladen...",
    saving: "Speichern...",
    save: "Speichern",
    saveAll: "Alle Änderungen Speichern",
    cancel: "Abbrechen",
    confirm: "Bestätigen",
    edit: "Bearbeiten",
    delete: "Löschen",
    error: "Fehler",
    success: "Erfolg",
    buyNow: "Jetzt Kaufen",
    outOfStock: "Ausverkauft",
    each: "jeweils",
    approve: "Genehmigen",
    reject: "Ablehnen",
    approvePublish: "Genehmigen und Veröffentlichen",
    rejectSubmission: "Einreichung Ablehnen",
    // Orders
    orders: "Bestellungen",
    orderDetails: "Bestelldetails",
    ordersDescription: "Verwalten und überprüfen Sie alle im Shop aufgegebenen Bestellungen",
    customer: "Kunde",
    email: "E-Mail",
    customerName: "Name",
    paymentInfo: "Zahlungsinformationen",
    paymentId: "Zahlungs-ID",
    reference: "Referenz",
    paymentStatus: "Status",
    paymentMethod: "Methode",
    paidAt: "Bezahlt",
    products: "Produkte",
    quantity: "Menge",
    totalOrders: "Gesamt Bestellungen",
    totalRevenue: "Gesamterlös",
    grossRevenue: "Bruttoerlös",
    netRevenue: "Nettoerlös",
    afterMPFees: "Nach Mercado Pago Gebühren",
    productsSold: "Verkaufte Produkte",
    approvedOrders: "Genehmigte Bestellungen",
    soldCards: "Verkaufte Karten",
    searchOrders: "Suche nach E-Mail, Zahlungs-ID oder Referenz...",
    allOrders: "Alle Bestellungen",
    noOrders: "Noch keine Bestellungen",
    noOrdersFound: "Keine Bestellungen gefunden",
    loadingOrders: "Bestellungen werden geladen...",
    view: "Ansehen",
    date: "Datum",
    items: "Artikel",
    status: "Status",
    // Admin Login
    password: "Passwort",
    emailPlaceholder: "admin@beispiel.com",
    passwordPlaceholder: "••••••••",
    login: "Anmelden",
    loggingIn: "Anmeldung läuft...",
    loginNote: "Wenn Sie kein Admin-Konto haben, wenden Sie sich an den Systemadministrator.",
    // Admin Submissions
    enterRejectionReason: "Ablehnungsgrund eingeben...",
    // Admin Inventory
    noChanges: "Keine Änderungen",
    noStockChanges: "Keine Bestandsänderungen zu speichern",
    actions: "Aktionen",
    // Status
    approved: "Genehmigt",
    pending: "Ausstehend",
    rejected: "Abgelehnt",
    cancelled: "Storniert",
    refunded: "Erstattet",
    // Inventory
    inventoryManagement: "Bestandsverwaltung",
    inventoryDescription: "Verwalten Sie Lagerbestände und Preise aller Karten",
    importCards: "Karten von API Importieren",
    importing: "Importierung...",
    totalCards: "Gesamt Karten",
    normalStock: "Normaler Bestand",
    foilStock: "Foil Bestand",
    inventoryValue: "Inventarwert",
    searchInventory: "Nach Name, Kartennummer oder Set suchen...",
    stockStatus: "Bestandsstatus",
    allStock: "Aller Bestand",
    allStockStatus: "Alle Status",
    inStock: "Auf Lager",
    lowStock: "Niedriger Bestand",
    stockType: "Bestandstyp",
    hasNormal: "Hat Normalen Bestand",
    hasFoil: "Hat Foil Bestand",
    hasBoth: "Hat Beide",
    all: "Alle",
    allTypes: "Alle Typen",
    allSets: "Alle Sets",
    allRarities: "Alle Seltenheiten",
    clearFilters: "Filter Löschen",
    showingCards: "Anzeige",
    ofCards: "von",
    cards: "karten",
    price: "Preis",
    foilPriceLabel: "Foil Preis",
    name: "Name",
    cardNum: "Karte #",
    // Stock badges
    lowStockBadge: "Niedriger Bestand",
    outOfStockBadge: "Ausverkauft",
    // Public Login
    signIn: "Anmelden",
    signInWith: "Weiter mit",
    google: "Google",
    signInToSubmit: "Melden Sie sich an, um Karten einzureichen",
    signInRequired: "Anmeldung erforderlich",
    signInRequiredDesc: "Erstellen Sie ein Konto oder melden Sie sich an, um Kartenvorschläge für unseren Katalog einzureichen.",
    createAccount: "Konto Erstellen",
    alreadyHaveAccount: "Haben Sie bereits ein Konto?",
    dontHaveAccount: "Haben Sie kein Konto?",
    signUp: "Registrieren",
    welcomeBack: "Willkommen zurück!",
    welcomeMessage: "Melden Sie sich mit Ihrem Google-Konto an, um fortzufahren",
    noAccountNeeded: "Kein Konto erforderlich - Ihr Google-Konto reicht aus",
    // My Submissions
    mySubmissions: "Meine Einreichungen",
    mySubmissionsDesc: "Verwalten Sie Ihre eingereichten Kartenvorschläge",
    noSubmissions: "Sie haben noch keine Karten eingereicht",
    noSubmissionsDesc: "Wenn Sie Karten zum Verkauf einreichen, werden sie hier angezeigt",
    submissionDetails: "Einreichungsdetails",
    viewDetails: "Details Anzeigen",
    submissionStatus: "Einreichungsstatus",
    statusPending: "Überprüfung ausstehend",
    statusApproved: "Genehmigt - Zum Katalog hinzugefügt",
    statusRejected: "Abgelehnt",
    rejectionReason: "Ablehnungsgrund",
    submittedOn: "Eingereicht am",
    reviewedOn: "Überprüft am",
    // User Menu
    myAccount: "Mein Konto",
    myProfile: "Mein Profil",
    signOut: "Abmelden",
    adminPanel: "Admin-Panel",
    // User Management
    userManagement: "Benutzerverwaltung",
    userManagementDesc: "Benutzerrollen und Berechtigungen verwalten",
    allUsers: "Alle Benutzer",
    totalUsers: "Gesamtbenutzer",
    adminUsers: "Admins",
    regularUsers: "Reguläre Benutzer",
    searchUsers: "Nach Name oder E-Mail suchen...",
    userEmail: "E-Mail",
    userName: "Name",
    userRole: "Rolle",
    userSince: "Registriert",
    lastLogin: "Letzte Anmeldung",
    makeAdmin: "Zum Admin machen",
    removeAdmin: "Admin entfernen",
    confirmMakeAdmin: "Sind Sie sicher, dass Sie diesen Benutzer zum Admin machen möchten?",
    confirmRemoveAdmin: "Sind Sie sicher, dass Sie die Admin-Rechte dieses Benutzers entfernen möchten?",
    adminRoleAssigned: "Admin-Rolle erfolgreich zugewiesen",
    adminRoleRemoved: "Admin-Rolle erfolgreich entfernt",
    temporaryPassword: "Temporäres Passwort",
    sharePasswordWithUser: "Teilen Sie dieses Passwort mit dem Benutzer, damit er sich mit E-Mail/Passwort anmelden kann. Er kann auch weiterhin Google OAuth verwenden.",
    userCanAlsoUseOAuth: "Hinweis: Der Benutzer kann sich auch mit Google OAuth anmelden (kein Passwort erforderlich).",
    copy: "Kopieren",
    copied: "Kopiert!",
    passwordCopied: "Passwort in die Zwischenablage kopiert",
    close: "Schließen",
    cannotRemoveSelf: "Sie können Ihre eigene Admin-Rolle nicht entfernen",
    noUsersFound: "Keine Benutzer gefunden",
    admin: "Admin",
    user: "Benutzer",
    // Auth Required Messages
    loginToView: "Melden Sie sich an, um diese Seite anzuzeigen",
    loginToContinue: "Melden Sie sich an, um fortzufahren",
    authenticationRequired: "Authentifizierung erforderlich",
    // My Collection
    myCollection: "Meine Sammlung",
    myCollectionDesc: "Verfolgen Sie Ihre Lorcana-Kartensammlung und Wunschliste",
    owned: "Ich Besitze",
    wanted: "Ich Möchte",
    ownedCards: "Karten die ich Besitze",
    wantedCards: "Karten die ich Möchte",
    noOwnedCards: "Sie haben noch keine Karten in Ihrer Sammlung",
    noWantedCards: "Sie haben keine Karten in Ihrer Wunschliste",
    addToCollection: "Zur Sammlung Hinzufügen",
    removeFromCollection: "Aus Sammlung Entfernen",
    addToOwned: "Ich Habe Diese",
    addToWanted: "Ich Möchte Diese",
    removeFromOwned: "Aus Besitz Entfernen",
    removeFromWanted: "Aus Wunschliste Entfernen",
    alreadyOwned: "Bereits in Sammlung",
    alreadyWanted: "Bereits in Wunschliste",
    addedToCollection: "Zu Ihrer Sammlung hinzugefügt",
    addedToWishlist: "Zu Ihrer Wunschliste hinzugefügt",
    removedFromCollection: "Aus Ihrer Sammlung entfernt",
    addedToCart: "zum Warenkorb hinzugefügt",
    removedFromWishlist: "Aus Ihrer Wunschliste entfernt",
    collectionStats: "Sammlungsstatistiken",
    totalOwned: "Gesamtkarten im Besitz",
    totalWanted: "Gesamtkarten Gewünscht",
    collectionValue: "Sammlungswert",
    mostWanted: "Meistgewünscht",
    recentlyAdded: "Kürzlich Hinzugefügt",
    viewInCatalog: "Im Katalog Anzeigen",
    markAsOwned: "Als Besitz Markieren",
    markAsWanted: "Als Gewünscht Markieren",
    quantity: "Menge",
    updateQuantity: "Menge Aktualisieren",
    addNotes: "Notizen Hinzufügen",
    cardNotes: "Notizen",
    notesPlaceholder: "Kartenzustand, Sprache, besondere Merkmale...",
    allCards: "Alle Karten",
    allCardsDesc: "Durchsuchen Sie alle Karten und fügen Sie sie zu Ihrer Sammlung hinzu",
    normal: "Normal",
    foil: "Foil",
    addNormal: "Normal Hinzufügen",
    addFoil: "Foil Hinzufügen",
    increaseQuantity: "Menge erhöhen",
    decreaseQuantity: "Menge verringern",
    missingCards: "Fehlende Karten",
    missingCardsDesc: "Karten, die Sie noch nicht in Ihrer Sammlung haben",
    noMissingCards: "Sie haben alle Karten!",
    totalMissing: "Gesamt Fehlend",
    // Shipping
    shippingMethod: "Versandmethode",
    shippingAddress: "Lieferadresse",
    shippingZone: "Versandzone",
    shippingCost: "Versandkosten",
    freeShipping: "KOSTENLOSER VERSAND",
    freeShippingInfo: "Hinzufügen, um kostenlosen Versand freizuschalten",
    estimatedDelivery: "Geschätzte Lieferung",
    businessDays: "Werktage",
    street: "Straße",
    number: "Nummer",
    commune: "Gemeinde",
    city: "Stadt",
    region: "Region",
    postalCode: "Postleitzahl",
    optional: "Optional",
    deliveryNotes: "Lieferhinweise",
    free: "KOSTENLOS",
    subtotal: "Zwischensumme",
    inCart: "im Warenkorb",
    available: "verfügbar",
    maxStockReached: "Maximaler Bestand im Warenkorb",
    // Payment Section
    securePayment: "100% Sichere Zahlung",
    securePaymentDesc: "Wir akzeptieren alle Zahlungsmethoden über Mercado Pago",
    certifiedDeveloper: "Zertifizierter Entwickler",
    mercadoPagoCheckoutPro: "Mercado Pago Checkout Pro",
    acceptedPaymentMethods: "Akzeptierte Zahlungsmethoden:",
    creditDebitCards: "💳 Kredit- und Debitkarten",
    bankTransfer: "🏦 Banküberweisung",
    mercadoPagoBalance: "📱 Mercado Pago Guthaben",
    // Products Page
    productsTitle: "Lorcana Produkte",
    productsSubtitle: "Booster, Spielmatten, Hüllen, Deckboxen und mehr",
    productFound: "Produkt gefunden",
    productsFound: "Produkte gefunden",
    viewProducts: "Produkte Anzeigen",
    productNotFound: "Das gesuchte Produkt existiert nicht.",
    productNotFoundTitle: "Produkt Nicht Gefunden",
    productUnavailable: "Dieses Produkt ist derzeit nicht verfügbar.",
    securePaymentWithMP: "100% sichere Zahlung mit Mercado Pago",
    paymentMethodsShort: "Kreditkarten, Debitkarten und Banküberweisung",
    // Contact Page
    contactAndHours: "Kontakt und Öffnungszeiten",
    contactSubtitle: "Haben Sie Fragen? Wir sind hier, um Ihnen zu helfen",
    contactMethods: "Kontaktmöglichkeiten",
    emailDescription: "Schreiben Sie uns bei Fragen",
    phoneDescription: "Rufen Sie uns an oder senden Sie uns eine WhatsApp",
    businessHours: "Öffnungszeiten",
    hoursWeekday: "Montag bis Samstag: 10:00 - 20:00",
    hoursWeekend: "Sonntag: Geschlossen",
    phone: "Telefon",
    // Catalog Page
    cardTypes: "Kartentypen",
    unitAvailable: "Einheit verfügbar",
    unitsAvailable: "Einheiten verfügbar",
  },
  es: {
    home: "Inicio",
    catalog: "Catálogo",
    filtersAndSort: "Filtros y Orden",
    loadingCards: "Cargando cartas...",
    loadingText: "Cargando...",
    cardFound: "carta",
    cardsFound: "cartas",
    foundText: "encontradas",
    noCardsFound: "No se encontraron cartas que coincidan con tus filtros",
    noCardsSearch: "No se encontraron cartas que coincidan con tu búsqueda.",
    submitCardInstead: "Envía Tu Carta en su Lugar",
    news: "Noticias",
    contact: "Contacto",
    search: "Buscar por nombre o número...",
    cart: "Carrito",
    emptyCart: "Tu carrito está vacío",
    checkout: "Finalizar Compra",
    total: "Total",
    minimumPurchase: "El monto mínimo de compra es $50 CLP",
    checkoutError: "Fallo al procesar la compra. Por favor intenta de nuevo.",
    toggleTheme: "Cambiar tema",
    lightMode: "Claro",
    darkMode: "Oscuro",
    systemMode: "Sistema",
    heroTitle: "Encuentra tu carta Lorcana perfecta",
    heroSubtitle: "Descubre, filtra y colecciona tus cartas favoritas",
    browseCatalog: "Explorar cartas",
    // Guided Tour
    tourNavigation: "Aquí puedes explorar productos de Lorcana. Navega por el catálogo, productos y más.",
    tourCatalog: "Explora nuestro catálogo completo de cartas Lorcana con precios actualizados.",
    tourLogin: "Para guardar tus cartas y crear colecciones, inicia sesión aquí. Es gratis y rápido.",
    tourCollection: "En 'Mi Colección' verás tus cartas guardadas, valores y listas personalizadas.",
    back: "Atrás",
    next: "Siguiente",
    skip: "Omitir",
    finish: "Finalizar",
    close: "Cerrar",
    haveACard: "¿Tienes una Carta para Vender?",
    haveACardDesc: "Envía tus cartas Lorcana a nuestro catálogo y las revisaremos para incluirlas en nuestra tienda.",
    error: "Error",
    cancel: "Cancelar",
    confirm: "Confirmar",
    // Submit Card Form
    submitCard: "Enviar una Carta",
    submitCardDescription: "¿Tienes una carta que te gustaría agregar a nuestro catálogo? ¡Envíala para revisión!",
    cardInformation: "Información de la Carta",
    cardInformationDesc: "Completa los detalles sobre la carta que deseas enviar",
    cardName: "Nombre de la Carta",
    cardNamePlaceholder: "ej: Mickey Mouse - Brave Little Tailor",
    selectSet: "Selecciona un set",
    selectType: "Selecciona un tipo",
    selectRarity: "Selecciona rareza",
    unknown: "Desconocido / Otro",
    description: "Descripción",
    descriptionPlaceholder: "Ingresa las habilidades y descripción de la carta",
    imageUrl: "URL de Imagen",
    imageUrlHelp: "Pega un enlace a la imagen de la carta (opcional)",
    suggestedPrice: "Precio Sugerido (CLP)",
    suggestedPriceHelp: "Opcional - ¿Qué precio crees que es justo?",
    contactEmail: "Email de Contacto",
    contactEmailHelp: "Te notificaremos cuando tu envío sea revisado",
    additionalNotes: "Notas Adicionales",
    additionalNotesPlaceholder: "Cualquier información extra sobre la carta...",
    submitting: "Enviando...",
    submissionSuccess: "¡Envío Recibido!",
    submissionSuccessDesc: "¡Gracias! Tu carta ha sido enviada para revisión.",
    submissionReviewMessage: "Nuestro equipo revisará tu envío y serás notificado por email.",
    submitAnother: "Enviar Otra Carta",
    submissionError: "Fallo al enviar carta. Por favor intenta de nuevo.",
    fillRequiredFields: "Por favor completa todos los campos requeridos",
    editSubmission: "Editar Envío",
    editSubmissionDesc: "Revisa y modifica los detalles de la carta antes de aprobar",
    preview: "Vista Previa",
    previewDesc: "Cómo aparecerá la carta en el catálogo",
    untitled: "Carta Sin Título",
    submittedBy: "Enviado por",
    submittedAt: "Enviado el",
    success: "Éxito",
    submissionUpdated: "Envío actualizado exitosamente",
    saveChanges: "Guardar Cambios",
    // Home page features
    heroTitleWithProducts: "Cartas y Productos Lorcana en Chile",
    heroSubtitleWithProducts: "Cartas individuales y productos sellados nuevos. Todo 100% original y sellado de fábrica.",
    categoriesAvailable: "Categorías Disponibles",
    individualCards: "Cartas Individuales",
    individualCardsDesc: "Cartas sueltas de todas las rarezas. Versiones normal y foil disponibles. Stock actualizado en tiempo real.",
    sealedProducts: "Productos Sellados Nuevos",
    sealedProductsDesc: "Boosters, playmats, fundas, deck boxes y más. Todos nuestros productos son 100% originales y sellados de fábrica.",
    tcgAccessories: "Accesorios TCG",
    tcgAccessoriesDesc: "Todo lo que necesitas para jugar y proteger tus cartas. Fundas, deck boxes, dados y más accesorios premium.",
    whyBuyFromUs: "Por Qué Comprar con Nosotros",
    whyBuyFromUsDesc: "Stock actualizado, precios competitivos y envíos a todo Chile. Tu tienda de confianza para cartas y productos Disney Lorcana.",
    sealedProductsHighlight: "Productos 100% Sellados y Nuevos",
    sealedProductsHighlightDesc: "Todos nuestros productos sellados (boosters, playmats, fundas, etc.) son completamente nuevos y vienen sellados de fábrica. Garantizamos autenticidad y calidad en cada compra.",
    legendaryCards: "Cartas Legendarias",
    legendaryCardsDesc: "Descubre cartas raras y legendarias de todos los sets de Lorcana",
    foilVariants: "Variantes Foil",
    foilVariantsDesc: "Versiones premium foil con efectos holográficos impresionantes",
    advancedFilters: "Filtros Avanzados",
    advancedFiltersDesc: "Encuentra exactamente lo que necesitas con herramientas de búsqueda potentes",
    filters: "Filtros",
    type: "Tipo",
    set: "Set / Colección",
    rarity: "Rareza",
    cardNumber: "Número de carta",
    language: "Idioma",
    priceRange: "Rango de precio",
    version: "Versión",
    versionAvailability: "Disponibilidad de Versión",
    allVersions: "Todas las Versiones",
    normalOnly: "Solo Normal",
    foilOnly: "Solo Foil",
    bothAvailable: "Ambas Disponibles",
    stockAvailability: "Disponibilidad de Stock",
    sortBy: "Ordenar por",
    gridView: "Vista de cuadrícula",
    listView: "Vista de lista",
    viewLabel: "Vista",
    addToCart: "Añadir al carrito",
    processing: "Procesando...",
    cardUnavailable: "Esta carta no está disponible actualmente en ninguna versión.",
    goBack: "Volver",
    normal: "Normal",
    foil: "Foil",
    character: "Personaje",
    item: "Objeto",
    action: "Acción",
    song: "Canción",
    common: "Común",
    uncommon: "Poco común",
    rare: "Raro",
    superRare: "Super Raro",
    legendary: "Legendario",
    enchanted: "Encantado",
    firstChapter: "El Primer Capítulo",
    riseOfFloodborn: "Ascenso de los Floodborn",
    intoInklands: "Hacia las Inklands",
    ursulaReturn: "El Regreso de Úrsula",
    shimmering: "Cielos Brillantes",
    azurite: "Mar Azurita",
    archazia: "Isla de Archazia",
    reignOfJafar: "Reinado de Jafar",
    fabled: "Fabled",
    whispersInTheWell: "Whispers in the Well",
    total: "Total",
    checkout: "Finalizar compra",
    emptyCart: "Tu carrito está vacío",
    about: "Acerca de",
    privacy: "Política de privacidad",
    copyright: "© 2025 GA Company. Todos los derechos reservados.",
    // Footer
    lorcanasingles: "Singles de Lorcana",
    links: "Enlaces",
    followUs: "Síguenos",
    nameAZ: "Nombre (A-Z)",
    nameZA: "Nombre (Z-A)",
    priceLowHigh: "Precio (Bajo a Alto)",
    priceHighLow: "Precio (Alto a Bajo)",
    raritySort: "Rareza",
    cardNumberLowHigh: "Número de Carta (Bajo a Alto)",
    cardNumberHighLow: "Número de Carta (Alto a Bajo)",
    // Common UI
    viewStore: "Ver Tienda",
    quantity: "Cantidad",
    loading: "Cargando...",
    loadingSubmissions: "Cargando envíos...",
    loadingLogs: "Cargando logs de actividad...",
    saving: "Guardando...",
    save: "Guardar",
    saveAll: "Guardar Todos los Cambios",
    cancel: "Cancelar",
    edit: "Editar",
    delete: "Eliminar",
    error: "Error",
    success: "Éxito",
    buyNow: "Comprar Ahora",
    outOfStock: "Sin Stock",
    each: "cada uno",
    approve: "Aprobar",
    reject: "Rechazar",
    approvePublish: "Aprobar y Publicar",
    rejectSubmission: "Rechazar Envío",
    // Orders
    orders: "Órdenes",
    orderDetails: "Detalles de la Orden",
    ordersDescription: "Gestiona y revisa todas las órdenes realizadas en la tienda",
    customer: "Cliente",
    email: "Email",
    customerName: "Nombre",
    paymentInfo: "Información de Pago",
    paymentId: "ID de Pago",
    reference: "Referencia",
    paymentStatus: "Estado",
    paymentMethod: "Método",
    paidAt: "Pagado",
    products: "Productos",
    quantity: "Cantidad",
    totalOrders: "Total Órdenes",
    totalRevenue: "Ingresos Totales",
    grossRevenue: "Ingresos brutos",
    netRevenue: "Ingresos Netos",
    afterMPFees: "Después de comisión de Mercado Pago",
    productsSold: "Productos Vendidos",
    approvedOrders: "Órdenes aprobadas",
    soldCards: "Cartas vendidas",
    searchOrders: "Buscar por email, payment ID o referencia...",
    allOrders: "Todas las Órdenes",
    noOrders: "No hay órdenes aún",
    noOrdersFound: "No se encontraron órdenes",
    loadingOrders: "Cargando órdenes...",
    view: "Ver",
    date: "Fecha",
    items: "Items",
    status: "Estado",
    // Admin Login
    password: "Contraseña",
    emailPlaceholder: "admin@ejemplo.com",
    passwordPlaceholder: "••••••••",
    login: "Iniciar Sesión",
    loggingIn: "Iniciando sesión...",
    loginNote: "Si no tienes cuenta de admin, contacta al administrador del sistema.",
    promotions: "Promociones",
    shipping: "Envíos",
    // Admin Submissions
    enterRejectionReason: "Ingresa la razón del rechazo...",
    // Admin Inventory
    noChanges: "Sin cambios",
    noStockChanges: "No hay cambios de stock para guardar",
    actions: "Acciones",
    // Admin Tools
    tools: "Herramientas",
    adminTools: "Herramientas Admin",
    updateOrderFees: "Actualizar Fees de Órdenes",
    processPayment: "Procesar Pago",
    inspectPayment: "Inspeccionar Pago",
    // Status
    approved: "Aprobado",
    pending: "Pendiente",
    rejected: "Rechazado",
    cancelled: "Cancelado",
    refunded: "Reembolsado",
    // Inventory
    inventoryManagement: "Gestión de Inventario",
    inventoryDescription: "Gestiona stock y precios de todas las cartas",
    importCards: "Importar Cartas desde API",
    importing: "Importando...",
    totalCards: "Total Cartas",
    normalStock: "Stock Normal",
    foilStock: "Stock Foil",
    inventoryValue: "Valor del Inventario",
    searchInventory: "Buscar por nombre, número de carta o set...",
    stockStatus: "Estado de Stock",
    allStock: "Todo el Stock",
    allStockStatus: "Todos los Estados",
    inStock: "Con Stock",
    lowStock: "Stock Bajo",
    stockType: "Tipo de Stock",
    hasNormal: "Tiene Stock Normal",
    hasFoil: "Tiene Stock Foil",
    hasBoth: "Tiene Ambos",
    all: "Todos",
    allTypes: "Todos los Tipos",
    allSets: "Todos los Sets",
    allRarities: "Todas las Rarezas",
    clearFilters: "Limpiar Filtros",
    showingCards: "Mostrando",
    ofCards: "de",
    cards: "cartas",
    price: "Precio",
    foilPriceLabel: "Precio Foil",
    name: "Nombre",
    cardNum: "Carta #",
    // Stock badges
    lowStockBadge: "Stock Bajo",
    outOfStockBadge: "Sin Stock",
    // Public Login
    signIn: "Iniciar Sesión",
    signInWith: "Continuar con",
    google: "Google",
    signInToSubmit: "Inicia sesión para enviar cartas",
    signInRequired: "Debes iniciar sesión",
    signInRequiredDesc: "Crea una cuenta o inicia sesión para enviar propuestas de cartas a nuestro catálogo.",
    createAccount: "Crear Cuenta",
    alreadyHaveAccount: "¿Ya tienes una cuenta?",
    dontHaveAccount: "¿No tienes una cuenta?",
    signUp: "Registrarse",
    welcomeBack: "¡Bienvenido de nuevo!",
    welcomeMessage: "Inicia sesión con tu cuenta de Google para continuar",
    noAccountNeeded: "No necesitas crear cuenta - con tu cuenta de Google es suficiente",
    // My Submissions
    mySubmissions: "Mis Envíos",
    mySubmissionsDesc: "Gestiona tus propuestas de cartas enviadas",
    noSubmissions: "No has enviado ninguna carta aún",
    noSubmissionsDesc: "Cuando envíes cartas para vender, aparecerán aquí",
    submissionDetails: "Detalles del Envío",
    viewDetails: "Ver Detalles",
    submissionStatus: "Estado del Envío",
    statusPending: "Pendiente de revisión",
    statusApproved: "Aprobada - Añadida al catálogo",
    statusRejected: "Rechazada",
    rejectionReason: "Razón del rechazo",
    submittedOn: "Enviado el",
    reviewedOn: "Revisado el",
    // User Menu
    myAccount: "Mi Cuenta",
    myProfile: "Mi Perfil",
    signOut: "Cerrar Sesión",
    adminPanel: "Panel Admin",
    // User Management
    userManagement: "Gestión de Usuarios",
    userManagementDesc: "Gestiona roles y permisos de usuarios",
    allUsers: "Todos los Usuarios",
    totalUsers: "Total Usuarios",
    adminUsers: "Admins",
    regularUsers: "Usuarios Regulares",
    searchUsers: "Buscar por nombre o email...",
    userEmail: "Email",
    userName: "Nombre",
    userRole: "Rol",
    userSince: "Registrado",
    lastLogin: "Último Ingreso",
    makeAdmin: "Hacer Admin",
    removeAdmin: "Quitar Admin",
    confirmMakeAdmin: "¿Estás seguro de que quieres hacer admin a este usuario?",
    confirmRemoveAdmin: "¿Estás seguro de que quieres quitar los privilegios de admin a este usuario?",
    adminRoleAssigned: "Rol de admin asignado exitosamente",
    adminRoleRemoved: "Rol de admin removido exitosamente",
    temporaryPassword: "Contraseña Temporal",
    sharePasswordWithUser: "Comparte esta contraseña con el usuario para que pueda iniciar sesión con email/contraseña. También puede continuar usando Google OAuth.",
    userCanAlsoUseOAuth: "Nota: El usuario también puede iniciar sesión usando Google OAuth (no necesita contraseña).",
    copy: "Copiar",
    copied: "¡Copiado!",
    passwordCopied: "Contraseña copiada al portapapeles",
    close: "Cerrar",
    cannotRemoveSelf: "No puedes quitar tu propio rol de admin",
    noUsersFound: "No se encontraron usuarios",
    admin: "Admin",
    user: "Usuario",
    // Auth Required Messages
    loginToView: "Inicia sesión para ver esta página",
    loginToContinue: "Inicia sesión para continuar",
    authenticationRequired: "Se requiere autenticación",
    // My Collection
    myCollection: "Mi Colección",
    myCollectionDesc: "Gestiona tu colección de cartas Lorcana y lista de deseos",
    owned: "Tengo",
    wanted: "Deseo",
    ownedCards: "Cartas que Tengo",
    wantedCards: "Cartas que Deseo",
    noOwnedCards: "No tienes ninguna carta en tu colección aún",
    noWantedCards: "No tienes ninguna carta en tu lista de deseos",
    addToCollection: "Agregar a Colección",
    removeFromCollection: "Quitar de Colección",
    addToOwned: "La Tengo",
    addToWanted: "La Deseo",
    removeFromOwned: "Quitar de Tengo",
    removeFromWanted: "Quitar de Deseo",
    alreadyOwned: "Ya en colección",
    alreadyWanted: "Ya en lista de deseos",
    addedToCollection: "Agregada a tu colección",
    addedToWishlist: "Agregada a tu lista de deseos",
    removedFromCollection: "Quitada de tu colección",
    addedToCart: "agregada al carrito",
    removedFromWishlist: "Quitada de tu lista de deseos",
    collectionStats: "Estadísticas de Colección",
    totalOwned: "Total de Cartas que Tengo",
    totalWanted: "Total de Cartas que Deseo",
    collectionValue: "Valor de la Colección",
    mostWanted: "Más Deseadas",
    recentlyAdded: "Agregadas Recientemente",
    viewInCatalog: "Ver en Catálogo",
    markAsOwned: "Marcar como Tengo",
    markAsWanted: "Marcar como Deseo",
    quantity: "Cantidad",
    updateQuantity: "Actualizar Cantidad",
    addNotes: "Agregar Notas",
    cardNotes: "Notas",
    notesPlaceholder: "Condición de la carta, idioma, características especiales...",
    allCards: "Todas las Cartas",
    allCardsDesc: "Explora todas las cartas y agrégalas a tu colección",
    normal: "Normal",
    foil: "Foil",
    addNormal: "Agregar Normal",
    addFoil: "Agregar Foil",
    increaseQuantity: "Aumentar cantidad",
    decreaseQuantity: "Disminuir cantidad",
    missingCards: "Cartas Faltantes",
    missingCardsDesc: "Cartas que aún no tienes en tu colección",
    noMissingCards: "¡Tienes todas las cartas!",
    totalMissing: "Total Faltantes",
    // Shipping
    shippingMethod: "Método de Envío",
    shippingAddress: "Dirección de Envío",
    shippingZone: "Zona de Envío",
    shippingCost: "Costo de Envío",
    freeShipping: "ENVÍO GRATIS",
    freeShippingInfo: "Agrega para desbloquear envío gratis",
    estimatedDelivery: "Entrega estimada",
    businessDays: "días hábiles",
    street: "Calle",
    number: "Número",
    commune: "Comuna",
    city: "Ciudad",
    region: "Región",
    postalCode: "Código Postal",
    optional: "Opcional",
    deliveryNotes: "Notas de Entrega",
    free: "GRATIS",
    subtotal: "Subtotal",
    inCart: "en carrito",
    available: "disponibles",
    maxStockReached: "Stock máximo en carrito",
    // Payment Section
    securePayment: "Pago 100% Seguro",
    securePaymentDesc: "Aceptamos todos los métodos de pago a través de Mercado Pago",
    certifiedDeveloper: "Desarrollador Certificado",
    mercadoPagoCheckoutPro: "Mercado Pago Checkout Pro",
    acceptedPaymentMethods: "Métodos de pago aceptados:",
    creditDebitCards: "💳 Tarjetas de crédito y débito",
    bankTransfer: "🏦 Transferencia bancaria",
    mercadoPagoBalance: "📱 Saldo de Mercado Pago",
    // Products Page
    productsTitle: "Productos Lorcana",
    productsSubtitle: "Boosters, Play Mats, Fundas, Deck Boxes y más",
    productFound: "producto encontrado",
    productsFound: "productos encontrados",
    viewProducts: "Ver Productos",
    productNotFound: "El producto que buscas no existe.",
    productNotFoundTitle: "Producto no encontrado",
    productUnavailable: "Este producto no está disponible actualmente.",
    securePaymentWithMP: "Pago 100% seguro con Mercado Pago",
    paymentMethodsShort: "Tarjetas de crédito, débito y transferencia",
    // Contact Page
    contactAndHours: "Contacto y Horarios de Atención",
    contactSubtitle: "¿Tienes alguna pregunta? Estamos aquí para ayudarte",
    contactMethods: "Medios de Contacto",
    emailDescription: "Escríbenos para cualquier consulta",
    phoneDescription: "Llámanos o envíanos un WhatsApp",
    businessHours: "Horarios",
    hoursWeekday: "Lunes a Sábado: 10:00 AM - 8:00 PM",
    hoursWeekend: "Domingo: Cerrado",
    phone: "Teléfono",
    // Catalog Page
    cardTypes: "Tipos de Cartas",
    unitAvailable: "unidad disponible",
    unitsAvailable: "unidades disponibles",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  useEffect(() => {
    // Auto-detect browser language
    const browserLang = navigator.language.split("-")[0] as Language
    if (["en", "fr", "de", "es"].includes(browserLang)) {
      setLanguage(browserLang)
    }
  }, [])

  // Wrapper para setLanguage (sin tracking de eventos para reducir tráfico)
  const setLanguageWithTracking = (newLang: Language) => {
    setLanguage(newLang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage: setLanguageWithTracking, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}
